BurrTools: src/lib/assembler_0.cpp File Reference
assembler_0.cpp File Reference
#include "assembler_0.h"
#include "bt_assert.h"
#include "problem.h"
#include "puzzle.h"
#include "voxel.h"
#include "assembly.h"
#include "gridtype.h"
#include "../tools/xml.h"
#include <cstdlib>
#include <cstring>
#include "../config.h"
Macros
#define ASSEMBLER_VERSION "1.4"
Functions
void printMatrix (const std::vector< unsigned int > &upDown, const std::vector< unsigned int > &left, const std::vector< unsigned int > &right, const std::vector< unsigned int > &colCount, unsigned int varivoxelStart, unsigned int varivoxelEnd)
static voxel_c * addToCache (voxel_c *cache[], unsigned int *fill, voxel_c *piece)
static unsigned int getInt (const char *s, unsigned int *i)
static unsigned int getLong (const char *s, unsigned long *i)
Macro Definition Documentation
ASSEMBLER_VERSION
#define ASSEMBLER_VERSION "1.4"
Function Documentation
addToCache()
static voxel_c * addToCache (voxel_c * cache[], unsigned int * fill, voxel_c * piece) static
Referenced by assembler_1_c::prepare(), and assembler_0_c::prepare().
getInt()
static unsigned int getInt (const char * s, unsigned int * i) static
Referenced by assembler_0_c::setPosition().
getLong()
static unsigned int getLong (const char * s, unsigned long * i) static
Referenced by assembler_0_c::setPosition().
printMatrix()
void printMatrix (const std::vector< unsigned int > & upDown, const std::vector< unsigned int > & left, const std::vector< unsigned int > & right, const std::vector< unsigned int > & colCount, unsigned int varivoxelStart, unsigned int varivoxelEnd)
References down, and up.