BurrTools: src/lib/assembler_1.cpp File Reference
assembler_1.cpp File Reference
#include "assembler_1.h"
#include "bt_assert.h"
#include "problem.h"
#include "puzzle.h"
#include "voxel.h"
#include "assembly.h"
#include "gridtype.h"
#include "../tools/xml.h"
#include <cstdlib>
Macros
#define ASSEMBLER_VERSION "2.0"
Functions
void printMatrix (const std::vector< unsigned int > &up, const std::vector< unsigned int > &down, const std::vector< unsigned int > &left, const std::vector< unsigned int > &right, const std::vector< unsigned int > &colCount, const std::vector< unsigned int > &weight, const std::vector< unsigned int > &min, const std::vector< unsigned int > &max)
static voxel_c * addToCache (voxel_c *cache[], unsigned int *fill, voxel_c *piece)
static bool betterParams (int n_sum, int, int n_max, int o_sum, int, int o_max)
static unsigned int getInt (const char *s, unsigned int *i)
static int stringToVector (const char *string, std::vector< unsigned int > &v)
static void vectorToStream (const std::vector< unsigned int > &v, std::ostream &str)
Macro Definition Documentation
ASSEMBLER_VERSION
#define ASSEMBLER_VERSION "2.0"
Function Documentation
addToCache()
static voxel_c * addToCache (voxel_c * cache[], unsigned int * fill, voxel_c * piece) static
betterParams()
static bool betterParams (int n_sum, int , int n_max, int o_sum, int , int o_max) static
Referenced by assembler_1_c::find_best_unclosed_column().
getInt()
static unsigned int getInt (const char * s, unsigned int * i) static
Referenced by stringToVector().
printMatrix()
void printMatrix (const std::vector< unsigned int > & up, const std::vector< unsigned int > & down, const std::vector< unsigned int > & left, const std::vector< unsigned int > & right, const std::vector< unsigned int > & colCount, const std::vector< unsigned int > & weight, const std::vector< unsigned int > & min, const std::vector< unsigned int > & max)
References down, max(), min(), and up.
stringToVector()
static int stringToVector (const char * string, std::vector< unsigned int > & v) static
References getInt().
Referenced by assembler_1_c::setPosition().
vectorToStream()
static void vectorToStream (const std::vector< unsigned int > & v, std::ostream & str) static
Referenced by assembler_1_c::save().