BurrTools: src/lib/bitfield_test.cpp File Reference
bitfield_test.cpp File Reference
#include "bitfield.h"
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (bitfield_test)
Function Documentation
BOOST_AUTO_TEST_CASE()
BOOST_AUTO_TEST_CASE (bitfield_test)
References bitfield_c< bits >::clear(), bitfield_c< bits >::get(), bitfield_c< bits >::notNull(), bitfield_c< bits >::reset(), and bitfield_c< bits >::set().