BurrTools: gzstreambuf Class Reference
gzstreambuf Class Reference
#include <gzstream.h>
Public Member Functions
gzstreambuf ()
int is_open ()
gzstreambuf * open (const char *name, int open_mode)
gzstreambuf * close ()
~gzstreambuf ()
virtual int overflow (int c=EOF)
virtual int underflow ()
virtual int sync ()
Private Member Functions
int flush_buffer ()
Private Attributes
gzFile file
char buffer [bufferSize]
char opened
int mode
Static Private Attributes
static const int bufferSize = 47+256
Constructor & Destructor Documentation
gzstreambuf()
gzstreambuf::gzstreambuf () inline
References buffer, and bufferSize.
~gzstreambuf()
gzstreambuf::~gzstreambuf () inline
References close().
Member Function Documentation
close()
gzstreambuf * gzstreambuf::close ()
References file, is_open(), opened, and sync().
Referenced by gzstreambase::close(), gzstreambase::~gzstreambase(), and ~gzstreambuf().
flush_buffer()
int gzstreambuf::flush_buffer () private
References file.
Referenced by overflow(), and sync().
is_open()
int gzstreambuf::is_open () inline
References opened.
Referenced by close(), gzstreambase::close(), and open().
open()
gzstreambuf * gzstreambuf::open (const char * name, int open_mode)
References file, is_open(), mode, and opened.
Referenced by gzstreambase::open().
overflow()
int gzstreambuf::overflow (int c = EOF) virtual
References flush_buffer(), mode, and opened.
sync()
int gzstreambuf::sync () virtual
References flush_buffer().
Referenced by close().
underflow()
int gzstreambuf::underflow () virtual
References buffer, bufferSize, file, mode, and opened.
Member Data Documentation
buffer
char gzstreambuf::buffer[bufferSize] private
Referenced by gzstreambuf(), and underflow().
bufferSize
const int gzstreambuf::bufferSize = 47+256 static private
Referenced by gzstreambuf(), and underflow().
file
gzFile gzstreambuf::file private
Referenced by close(), flush_buffer(), open(), and underflow().
mode
int gzstreambuf::mode private
Referenced by open(), overflow(), and underflow().
opened
char gzstreambuf::opened private
Referenced by close(), is_open(), open(), overflow(), and underflow().
The documentation for this class was generated from the following files:
src/tools/gzstream.h
src/tools/gzstream.cpp