BurrTools: assembler_0_c Class Reference
assembler_0_c Class Reference
This is an assembler class.
#include <assembler_0.h>
Classes
class piecePosition
Public Member Functions
assembler_0_c (const problem_c &problem)
~assembler_0_c (void)
errState createMatrix (bool keepMirror, bool keepRotations, bool complete)
the part of the initialisation that may take a while.
void assemble (assembler_cb *callback)
start the assembly process.
int getErrorsParam (void)
when createMatrix returns an error you can call this function to find out which piece is involved, or other additional information
virtual float getFinished (void) const
a function that returns the finished percentage in the range between 0 and 1.
virtual void stop (void)
stops the assembly process sometimes in the near future.
virtual bool stopped (void) const
returns true, as soon as the process really has stopped
virtual errState setPosition (const char *string, const char *version)
sets the position of the assembly process, so that it continues exactly where it stood, when getPosition was called
virtual void save (xmlWriter_c &xml) const
this function saves the current state of the assembler into an xml node to write it to an file.
virtual void reduce (void)
Try to optimise piece placement.
virtual unsigned int getReducePiece (void) const
Then running in an extra thread it is possible to find out which piece is worked on by reduce.
virtual unsigned long getIterations (void)
this function returns a number reflecting the complexity of the puzzle.
bool getPiecePlacementSupported (void) const
unsigned int getPiecePlacement (unsigned int node, int delta, unsigned int piece, unsigned char *tran, int *x, int *y, int *z) const
unsigned int getPiecePlacementCount (unsigned int piece) const
void debug_step (unsigned long num=1)
assembly_c * getAssembly (void)
Public Member Functions inherited from assembler_c
assembler_c (void)
initialisation, only the things that can be done quickly are done here
virtual ~assembler_c (void)
Static Public Member Functions
static bool canHandle (const problem_c &p)
Protected Member Functions
void GenerateFirstRow (void)
int AddPieceNode (unsigned int piece, unsigned int rot, unsigned int x, unsigned int y, unsigned int z)
void getPieceInformation (unsigned int node, unsigned char *tran, int *x, int *y, int *z, unsigned int *pc) const
void AddVoxelNode (unsigned int col, unsigned int piecenode)
unsigned int getRows (int pos)
unsigned int getRight (int pos)
unsigned int getColCount (int pos)
unsigned int getVarivoxelStart (void)
unsigned int getPos (void)
assembler_cb * getCallback (void)
unsigned int getPiecenumber (void)
void checkForTransformedAssemblies (unsigned int pivot, mirrorInfo_c *mir)
Protected Attributes
const problem_c & problem
Private Member Functions
void cover (unsigned int col)
void uncover (unsigned int col)
void cover_row (unsigned int r)
void uncover_row (unsigned int r)
bool try_cover_row (unsigned int r, unsigned int *columns)
void remove_row (unsigned int r)
void reinsert_row (unsigned int r)
void remove_column (unsigned int c)
void solution (void)
void iterativeMultiSearch (void)
bool canPlace (const voxel_c *piece, int x, int y, int z) const
int prepare (void)
this function prepares the matrix of nodes for the recursive function I've done some additions to Knuths algorithm to implement variable voxels (empty spaces in the solution) and multiple instances of the same piece.
bool checkmatrix (void)
unsigned int clumpify (void)
assembler_0_c (const assembler_0_c &)
void operator= (const assembler_0_c &)
Private Attributes
std::vector< unsigned int > left
std::vector< unsigned int > right
std::vector< unsigned int > upDown
std::vector< unsigned int > colCount
bool abbort
bool running
unsigned int pos
unsigned int * rows
unsigned int * columns
errState errorsState
int errorsParam
unsigned long iterations
int holes
unsigned int varivoxelStart
unsigned int varivoxelEnd
unsigned int piecenumber
assembler_cb * asm_bc
unsigned int reducePiece
std::vector< piecePosition > piecePositions
bool avoidTransformedAssemblies
unsigned int avoidTransformedPivot
mirrorInfo_c * avoidTransformedMirror
bool complete
set to true, when complete rotation analysis is requested
bool debug
int debug_loops
Additional Inherited Members
Public Types inherited from assembler_c
enum errState {
ERR_NONE , ERR_TOO_MANY_UNITS , ERR_TOO_FEW_UNITS , ERR_CAN_NOT_PLACE ,
ERR_CAN_NOT_RESTORE_VERSION , ERR_CAN_NOT_RESTORE_SYNTAX , ERR_PUZZLE_UNHANDABLE
}
the possible error conditions that can be found while preparing the puzzle
Detailed Description
This is an assembler class.
It is more or less identical to Don Knuths idea. Some changes have been done though to provide for holes. This class can not handle ranges or multi-pieces.
All involved pieces must be there exactly one time. But in that case it is a bit faster than assembler_1.
Constructor & Destructor Documentation
assembler_0_c() [1/2]
assembler_0_c::assembler_0_c (const problem_c & problem)
~assembler_0_c()
assembler_0_c::~assembler_0_c (void)
References avoidTransformedMirror, columns, and rows.
assembler_0_c() [2/2]
assembler_0_c::assembler_0_c (const assembler_0_c &) private
Member Function Documentation
AddPieceNode()
int assembler_0_c::AddPieceNode (unsigned int piece, unsigned int rot, unsigned int x, unsigned int y, unsigned int z) protected
References colCount, down, left, piecePositions, right, up, and upDown.
Referenced by prepare().
AddVoxelNode()
void assembler_0_c::AddVoxelNode (unsigned int col, unsigned int piecenode) protected
References colCount, down, left, right, up, and upDown.
Referenced by prepare().
assemble()
void assembler_0_c::assemble (assembler_cb *) virtual
start the assembly process.
it is intended that the assembly process runs in a different thread from the controlling thread. When this is the case the controlling thread can call stop to make the assembly thread stop working. It will then return from this function but can be resumed any time
Reimplemented from assembler_c.
References asm_bc, debug, assembler_c::ERR_NONE, errorsState, and iterativeMultiSearch().
canHandle()
bool assembler_0_c::canHandle (const problem_c & p) static
References problem_c::getNumberOfParts(), problem_c::getPartMaximum(), and problem_c::getPartMinimum().
Referenced by createMatrix(), and gridType_c::findAssembler().
canPlace()
bool assembler_0_c::canPlace (const voxel_c * piece, int x, int y, int z) const private
References voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), voxel_c::getColor(), getResultShape(), voxel_c::getState(), voxel_c::onGrid(), problem_c::placementAllowed(), problem, voxel_c::VX_EMPTY, and voxel_c::VX_FILLED.
Referenced by prepare().
checkForTransformedAssemblies()
void assembler_0_c::checkForTransformedAssemblies (unsigned int pivot, mirrorInfo_c * mir) protected
References avoidTransformedAssemblies, avoidTransformedMirror, and avoidTransformedPivot.
Referenced by prepare().
checkmatrix()
bool assembler_0_c::checkmatrix (void) private
References colCount, holes, right, and varivoxelEnd.
Referenced by reduce().
clumpify()
unsigned int assembler_0_c::clumpify (void) private
References columns, down, piecePositions, remove_column(), and right.
Referenced by reduce().
cover()
void assembler_0_c::cover (unsigned int col) private
References colCount, down, left, right, up, and upDown.
Referenced by cover_row(), iterativeMultiSearch(), reduce(), setPosition(), and try_cover_row().
cover_row()
void assembler_0_c::cover_row (unsigned int r) private
References colCount, cover(), and right.
Referenced by iterativeMultiSearch(), and setPosition().
createMatrix()
assembler_0_c::errState assembler_0_c::createMatrix (bool , bool , bool) virtual
the part of the initialisation that may take a while.
when keep mirror is true, the assembler must not throw away mirror solutions but it still removes solutions that are rotations.
Reimplemented from assembler_c.
References avoidTransformedAssemblies, avoidTransformedMirror, bt_assert, canHandle(), columns, complete, voxel_c::countState(), assembler_c::ERR_CAN_NOT_PLACE, assembler_c::ERR_NONE, assembler_c::ERR_PUZZLE_UNHANDABLE, assembler_c::ERR_TOO_FEW_UNITS, assembler_c::ERR_TOO_MANY_UNITS, errorsParam, errorsState, problem_c::getNumberOfParts(), problem_c::getNumberOfPieces(), problem_c::getPartShape(), getResultShape(), holes, iterations, piecenumber, pos, prepare(), problem, problem_c::resultValid(), rows, varivoxelEnd, varivoxelStart, voxel_c::VX_FILLED, and voxel_c::VX_VARIABLE.
debug_step()
void assembler_0_c::debug_step (unsigned long num = 1) virtual
Reimplemented from assembler_c.
References asm_bc, debug, debug_loops, and iterativeMultiSearch().
GenerateFirstRow()
void assembler_0_c::GenerateFirstRow (void) protected
References colCount, left, right, upDown, varivoxelEnd, and varivoxelStart.
Referenced by prepare().
getAssembly()
assembly_c * assembler_0_c::getAssembly (void) virtual
Implements assembler_c.
References assembly_c::addNonPlacement(), assembly_c::addPlacement(), bt_assert, puzzle_c::getGridType(), getPieceInformation(), getPiecenumber(), getPos(), problem_c::getPuzzle(), getRows(), piecenumber, pos, and problem.
Referenced by solution().
getCallback()
assembler_cb * assembler_0_c::getCallback (void) inline protected
References asm_bc.
Referenced by solution().
getColCount()
unsigned int assembler_0_c::getColCount (int pos) inline protected
References colCount, and pos.
getErrorsParam()
int assembler_0_c::getErrorsParam (void) inline virtual
when createMatrix returns an error you can call this function to find out which piece is involved, or other additional information
Reimplemented from assembler_c.
References errorsParam.
getFinished()
float assembler_0_c::getFinished (void) const virtual
a function that returns the finished percentage in the range between 0 and 1.
It must be possible to call this function while assemble is running
Reimplemented from assembler_c.
References colCount, columns, down, piecenumber, pos, rows, up, and upDown.
getIterations()
virtual unsigned long assembler_0_c::getIterations (void) inline virtual
this function returns a number reflecting the complexity of the puzzle.
This could be the number of placements tried, or some other value
Reimplemented from assembler_c.
References iterations.
getPieceInformation()
void assembler_0_c::getPieceInformation (unsigned int node, unsigned char * tran, int * x, int * y, int * z, unsigned int * pc) const protected
References bt_assert, and piecePositions.
Referenced by getAssembly(), and getPiecePlacement().
getPiecenumber()
unsigned int assembler_0_c::getPiecenumber (void) inline protected
References piecenumber.
Referenced by getAssembly().
getPiecePlacement()
unsigned int assembler_0_c::getPiecePlacement (unsigned int node, int delta, unsigned int piece, unsigned char * tran, int * x, int * y, int * z) const virtual
Reimplemented from assembler_c.
References bt_assert, down, getPieceInformation(), and up.
getPiecePlacementCount()
unsigned int assembler_0_c::getPiecePlacementCount (unsigned int piece) const virtual
Reimplemented from assembler_c.
References colCount.
getPiecePlacementSupported()
bool assembler_0_c::getPiecePlacementSupported (void) const inline virtual
Reimplemented from assembler_c.
getPos()
unsigned int assembler_0_c::getPos (void) inline protected
References pos.
Referenced by getAssembly().
getReducePiece()
virtual unsigned int assembler_0_c::getReducePiece (void) const inline virtual
Then running in an extra thread it is possible to find out which piece is worked on by reduce.
Because the reduce process can take a long time it is nice to give some feedback to the user. With this function the user can get a number to display with the information that the program is currently reducing. The intended interpretation is that the program is currently working on the piece with the returned number, but if you want you can also return something else
Reimplemented from assembler_c.
References reducePiece.
getRight()
unsigned int assembler_0_c::getRight (int pos) inline protected
References pos, and right.
getRows()
unsigned int assembler_0_c::getRows (int pos) inline protected
References pos, and rows.
Referenced by getAssembly().
getVarivoxelStart()
unsigned int assembler_0_c::getVarivoxelStart (void) inline protected
References varivoxelStart.
Referenced by prepare().
iterativeMultiSearch()
void assembler_0_c::iterativeMultiSearch (void) private
References abbort, colCount, columns, cover(), cover_row(), debug, debug_loops, down, holes, iterations, piecenumber, pos, right, rows, running, solution(), uncover(), uncover_row(), and varivoxelEnd.
Referenced by assemble(), and debug_step().
operator=()
void assembler_0_c::operator= (const assembler_0_c &) private
prepare()
int assembler_0_c::prepare (void) private
this function prepares the matrix of nodes for the recursive function I've done some additions to Knuths algorithm to implement variable voxels (empty spaces in the solution) and multiple instances of the same piece.
Empty voxels in the result are done by removing columns from the matrix. This will prevent the algorithm from filling the corresponding voxels. But we need to have the constraints that these columns place on the solution. This is done by adding these columns to the matrix but behind the normal columns. These additional columns wont be searched by the alg. if it looks for the next task to achieve.
Multiple instances of the same piece is handles in a similar way. To prevent finding the same solution again and again with just the pieces swapping places we number the pieces and their possible placements and disallow that the position number of piece n is lower than the position number of piece n-1. This can be achieved by adding more constraint columns. There need to be one column for each
negative result show there is something wrong: the place -result has not possible position inside the result
References AddPieceNode(), mirrorInfo_c::addPieces(), addToCache(), AddVoxelNode(), voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), canPlace(), checkForTransformedAssemblies(), columns, symmetries_c::countSymmetryIntersection(), GenerateFirstRow(), puzzle_c::getGridType(), voxel_c::getHx(), voxel_c::getHy(), voxel_c::getHz(), voxel_c::getIndex(), voxel_c::getMirrorTransform(), problem_c::getNumberOfParts(), problem_c::getNumberOfPieces(), symmetries_c::getNumTransformations(), symmetries_c::getNumTransformationsMirror(), problem_c::getPartShape(), problem_c::getPuzzle(), getResultShape(), problem_c::getShapeIdOfPart(), voxel_c::getState(), gridType_c::getSymmetries(), getVarivoxelStart(), gridType_c::getVoxel(), voxel_c::getXYZ(), piecenumber, problem, reducePiece, voxel_c::selfSymmetries(), symmetries_c::symmetrieContainsTransformation(), symmetries_c::symmetriesLeft(), symmetries_c::symmetryContainsMirror(), voxel_c::transform(), unSymmetric, voxel_c::VX_FILLED, and voxel_c::VX_VARIABLE.
Referenced by createMatrix().
reduce()
void assembler_0_c::reduce (void) virtual
Try to optimise piece placement.
the function tries to remove possible piece placements by checking if, after the piece has been placed somewhere, that all the other pieces still can be placed and all holes can still be filled. if this is not the case then this placement can be removed
it is not necessary for an assembler to implement this function
Reimplemented from assembler_c.
References checkmatrix(), clumpify(), colCount, columns, cover(), down, piecenumber, piecePositions, reducePiece, remove_row(), right, try_cover_row(), uncover(), uncover_row(), and varivoxelEnd.
reinsert_row()
void assembler_0_c::reinsert_row (unsigned int r) private
References colCount, down, right, and up.
remove_column()
void assembler_0_c::remove_column (unsigned int c) private
References down, left, and right.
Referenced by clumpify().
remove_row()
void assembler_0_c::remove_row (unsigned int r) private
References colCount, down, right, and up.
Referenced by reduce().
save()
void assembler_0_c::save (xmlWriter_c & xml) const virtual
this function saves the current state of the assembler into an xml node to write it to an file.
this state must be such that the class can restore this state and continue from there by getting this and the puzzle given to the constructor
Reimplemented from assembler_c.
References xmlWriter_c::addContent(), ASSEMBLER_VERSION, columns, xmlWriter_c::endTag(), iterations, xmlWriter_c::newAttrib(), xmlWriter_c::newTag(), piecenumber, pos, and rows.
setPosition()
assembler_c::errState assembler_0_c::setPosition (const char * string, const char * version) virtual
sets the position of the assembly process, so that it continues exactly where it stood, when getPosition was called
the function should only be called when assembly is not running it should be called before calling assemble
Reimplemented from assembler_c.
References ASSEMBLER_VERSION, bt_assert, columns, cover(), cover_row(), assembler_c::ERR_CAN_NOT_RESTORE_SYNTAX, assembler_c::ERR_CAN_NOT_RESTORE_VERSION, assembler_c::ERR_NONE, getInt(), getLong(), iterations, left, piecenumber, pos, and rows.
solution()
void assembler_0_c::solution (void) private
References assembler_cb::assembly(), avoidTransformedAssemblies, avoidTransformedMirror, avoidTransformedPivot, complete, getAssembly(), getCallback(), problem, and assembly_c::smallerRotationExists().
Referenced by iterativeMultiSearch().
stop()
virtual void assembler_0_c::stop (void) inline virtual
stops the assembly process sometimes in the near future.
Reimplemented from assembler_c.
References abbort.
stopped()
virtual bool assembler_0_c::stopped (void) const inline virtual
returns true, as soon as the process really has stopped
Reimplemented from assembler_c.
References running.
try_cover_row()
bool assembler_0_c::try_cover_row (unsigned int r, unsigned int * columns) private
References colCount, columns, cover(), left, right, uncover(), and varivoxelEnd.
Referenced by reduce().
uncover()
void assembler_0_c::uncover (unsigned int col) private
References colCount, down, left, right, up, and upDown.
Referenced by iterativeMultiSearch(), reduce(), try_cover_row(), and uncover_row().
uncover_row()
void assembler_0_c::uncover_row (unsigned int r) private
References colCount, left, and uncover().
Referenced by iterativeMultiSearch(), and reduce().
Member Data Documentation
abbort
bool assembler_0_c::abbort private
Referenced by iterativeMultiSearch(), and stop().
asm_bc
assembler_cb* assembler_0_c::asm_bc private
Referenced by assemble(), debug_step(), and getCallback().
avoidTransformedAssemblies
bool assembler_0_c::avoidTransformedAssemblies private
Referenced by checkForTransformedAssemblies(), createMatrix(), and solution().
avoidTransformedMirror
mirrorInfo_c* assembler_0_c::avoidTransformedMirror private
Referenced by checkForTransformedAssemblies(), createMatrix(), solution(), and ~assembler_0_c().
avoidTransformedPivot
unsigned int assembler_0_c::avoidTransformedPivot private
Referenced by checkForTransformedAssemblies(), and solution().
colCount
std::vector<unsigned int> assembler_0_c::colCount private
Referenced by AddPieceNode(), AddVoxelNode(), checkmatrix(), cover(), cover_row(), GenerateFirstRow(), getColCount(), getFinished(), getPiecePlacementCount(), iterativeMultiSearch(), reduce(), reinsert_row(), remove_row(), try_cover_row(), uncover(), and uncover_row().
columns
unsigned int* assembler_0_c::columns private
Referenced by clumpify(), createMatrix(), getFinished(), iterativeMultiSearch(), prepare(), reduce(), save(), setPosition(), try_cover_row(), and ~assembler_0_c().
complete
bool assembler_0_c::complete private
set to true, when complete rotation analysis is requested
Referenced by createMatrix(), and solution().
debug
bool assembler_0_c::debug private
Referenced by assemble(), debug_step(), and iterativeMultiSearch().
debug_loops
int assembler_0_c::debug_loops private
Referenced by debug_step(), and iterativeMultiSearch().
errorsParam
int assembler_0_c::errorsParam private
Referenced by createMatrix(), and getErrorsParam().
errorsState
errState assembler_0_c::errorsState private
Referenced by assemble(), and createMatrix().
holes
int assembler_0_c::holes private
Referenced by checkmatrix(), createMatrix(), and iterativeMultiSearch().
iterations
unsigned long assembler_0_c::iterations private
Referenced by createMatrix(), getIterations(), iterativeMultiSearch(), save(), and setPosition().
left
std::vector<unsigned int> assembler_0_c::left private
Referenced by AddPieceNode(), AddVoxelNode(), cover(), GenerateFirstRow(), remove_column(), setPosition(), try_cover_row(), uncover(), and uncover_row().
piecenumber
unsigned int assembler_0_c::piecenumber private
Referenced by createMatrix(), getAssembly(), getFinished(), getPiecenumber(), iterativeMultiSearch(), prepare(), reduce(), save(), and setPosition().
piecePositions
std::vector<piecePosition> assembler_0_c::piecePositions private
Referenced by AddPieceNode(), clumpify(), getPieceInformation(), and reduce().
pos
unsigned int assembler_0_c::pos private
Referenced by createMatrix(), getAssembly(), getColCount(), getFinished(), getPos(), getRight(), getRows(), iterativeMultiSearch(), save(), and setPosition().
problem
const problem_c& assembler_0_c::problem protected
Referenced by canPlace(), createMatrix(), getAssembly(), prepare(), and solution().
reducePiece
unsigned int assembler_0_c::reducePiece private
Referenced by getReducePiece(), prepare(), and reduce().
right
std::vector<unsigned int> assembler_0_c::right private
Referenced by AddPieceNode(), AddVoxelNode(), checkmatrix(), clumpify(), cover(), cover_row(), GenerateFirstRow(), getRight(), iterativeMultiSearch(), reduce(), reinsert_row(), remove_column(), remove_row(), try_cover_row(), and uncover().
rows
unsigned int* assembler_0_c::rows private
Referenced by createMatrix(), getFinished(), getRows(), iterativeMultiSearch(), save(), setPosition(), and ~assembler_0_c().
running
bool assembler_0_c::running private
Referenced by iterativeMultiSearch(), and stopped().
upDown
std::vector<unsigned int> assembler_0_c::upDown private
Referenced by AddPieceNode(), AddVoxelNode(), cover(), GenerateFirstRow(), getFinished(), and uncover().
varivoxelEnd
unsigned int assembler_0_c::varivoxelEnd private
Referenced by checkmatrix(), createMatrix(), GenerateFirstRow(), iterativeMultiSearch(), reduce(), and try_cover_row().
varivoxelStart
unsigned int assembler_0_c::varivoxelStart private
Referenced by createMatrix(), GenerateFirstRow(), and getVarivoxelStart().
The documentation for this class was generated from the following files:
src/lib/assembler_0.h
src/lib/assembler_0.cpp