BurrTools: movementCache_1_c Class Reference
movementCache_1_c Class Reference
movement cache for the triangle grid
#include <movementcache_1.h>
Public Member Functions
movementCache_1_c (const problem_c &puz)
Public Member Functions inherited from movementCache_c
movementCache_c (const problem_c &puz)
create the cache.
virtual ~movementCache_c (void)
void getMoValue (int dx, int dy, int dz, unsigned char t1, unsigned char t2, unsigned int p1, unsigned int p2, unsigned int *movements)
return the values, that are: how far can the 2nd piece be moved in positive x, y and z direction, when the 2nd piece is offset by dx, dy and dz relative to the first, the 2 pieces are the pieces p1 and p2 from the puzzle and problem defined in the constructor and the 2 pieces are transformed by t1 and t2
Private Member Functions
unsigned int * moCalcValues (const voxel_c *sh1, const voxel_c *sh2, int dx, int dy, int dz)
when the entry is not inside the table, this function calculates the values for the movement info
unsigned int numDirections (void)
return the number of different directions of movement that are possible within the space grid that that movement cache is for
void getDirection (unsigned int dir, int *x, int *y, int *z)
return the movement vector of the given direction
movementCache_1_c (const movementCache_1_c &)
void operator= (const movementCache_1_c &)
Detailed Description
movement cache for the triangle grid
Constructor & Destructor Documentation
movementCache_1_c() [1/2]
movementCache_1_c::movementCache_1_c (const problem_c & puz)
movementCache_1_c() [2/2]
movementCache_1_c::movementCache_1_c (const movementCache_1_c &) private
Member Function Documentation
getDirection()
void movementCache_1_c::getDirection (unsigned int dir, int * x, int * y, int * z) private virtual
return the movement vector of the given direction
Implements movementCache_c.
References bt_assert, dirs, and NUM_DIRECTIONS.
moCalcValues()
unsigned int * movementCache_1_c::moCalcValues (const voxel_c * sh1, const voxel_c * sh2, int dx, int dy, int dz) private virtual
when the entry is not inside the table, this function calculates the values for the movement info
Implements movementCache_c.
References voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), bt_assert, checks, dirs, voxel_c::getHx(), voxel_c::getHy(), voxel_c::getHz(), voxel_c::isEmpty(), voxel_c::isEmpty2(), voxel_c::isFilled2(), and NUM_DIRECTIONS.
numDirections()
unsigned int movementCache_1_c::numDirections (void) private virtual
return the number of different directions of movement that are possible within the space grid that that movement cache is for
Implements movementCache_c.
References NUM_DIRECTIONS.
operator=()
void movementCache_1_c::operator= (const movementCache_1_c &) private
The documentation for this class was generated from the following files:
src/lib/movementcache_1.h
src/lib/movementcache_1.cpp