BurrTools: nodeHash Class Reference
nodeHash Class Reference
This is a hashtable that stores disassemblerNode_c pointer.
#include <disassemblerhashes.h>
Public Member Functions
nodeHash (void)
~nodeHash (void)
void clear (void)
delete all nodes and empty table for new usage
const disassemblerNode_c * insert (disassemblerNode_c *n)
add a new node.
bool contains (const disassemblerNode_c *n) const
check, if a node is in the hashtable
Private Member Functions
nodeHash (const nodeHash &)
void operator= (const nodeHash &)
Private Attributes
unsigned long tab_size
current table size
unsigned long tab_entries
current number of entries
disassemblerNode_c ** tab
the hashtable
Detailed Description
This is a hashtable that stores disassemblerNode_c pointer.
The nodes will not become owned by the hashtable, but the table will use the reference counting system of the node
Constructor & Destructor Documentation
nodeHash() [1/2]
nodeHash::nodeHash (void)
References tab, tab_entries, and tab_size.
~nodeHash()
nodeHash::~nodeHash (void)
References clear(), and tab.
nodeHash() [2/2]
nodeHash::nodeHash (const nodeHash &) private
Member Function Documentation
clear()
void nodeHash::clear (void)
delete all nodes and empty table for new usage
References disassemblerNode_c::decRefCount(), disassemblerNode_c::next, tab, tab_entries, and tab_size.
Referenced by disassembler_0_c::disassemble_rec(), and ~nodeHash().
contains()
bool nodeHash::contains (const disassemblerNode_c * n) const
check, if a node is in the hashtable
References disassemblerNode_c::hash(), disassemblerNode_c::next, tab, and tab_size.
insert()
const disassemblerNode_c * nodeHash::insert (disassemblerNode_c * n)
add a new node.
Returns the node pointer of the identical node found or 0
References disassemblerNode_c::getWaylength(), disassemblerNode_c::hash(), disassemblerNode_c::incRefCount(), disassemblerNode_c::next, disassemblerNode_c::replaceNode(), tab, tab_entries, and tab_size.
Referenced by disassembler_0_c::disassemble_rec().
operator=()
void nodeHash::operator= (const nodeHash &) private
Member Data Documentation
tab
disassemblerNode_c** nodeHash::tab private
the hashtable
Referenced by clear(), contains(), insert(), nodeHash(), and ~nodeHash().
tab_entries
unsigned long nodeHash::tab_entries private
current number of entries
Referenced by clear(), insert(), and nodeHash().
tab_size
unsigned long nodeHash::tab_size private
current table size
Referenced by clear(), contains(), insert(), and nodeHash().
The documentation for this class was generated from the following files:
src/lib/disassemblerhashes.h
src/lib/disassemblerhashes.cpp