BurrTools: separationInfo_c Class Reference
separationInfo_c Class Reference
this class is used to store the complexity of a disassembly.
#include <disassembly.h>
Public Member Functions
separationInfo_c (xmlParser_c &pars)
load separationInfo from parser
separationInfo_c (const separation_c *sep)
create a separation info from a normal separation
void save (xmlWriter_c &xml) const
save into an xml node
virtual unsigned int sumMoves (void) const
the number of moves to completely disassemble the puzzle, including all sub separations
virtual void movesText (char *txt, int len) const
fill a string with dot separated numbers containing the moves required to disassemble the puzzle not more than len characters are written
virtual unsigned int getSequenceLength (unsigned int x) const
helper function used for "compare" to get the number of moves for the x-th place in the string
virtual unsigned int getNumSequences (void) const
helper function used for "compare" to get the number of move sequences
Public Member Functions inherited from disassembly_c
disassembly_c (void)
virtual ~disassembly_c (void)
int compare (const disassembly_c *s2) const
compares this and the given separation, for a higher level.
Private Member Functions
bool containsMultiMoves (unsigned int root) const
used in movesText to find out if a branch has a move sequence longer than 1
void recursiveConstruction (const separation_c *sep)
used in constructor for create separationInfo from normal separation
int movesText2 (char *txt, int len, unsigned int idx) const
separationInfo_c (const separationInfo_c &)
void operator= (const separationInfo_c &)
Private Attributes
std::vector< unsigned int > values
this array contains the whole disassembly tree in prefix order, root, left, removed.
Additional Inherited Members
Detailed Description
this class is used to store the complexity of a disassembly.
it is used as a memory efficient replacement for the basic information in separation_c without the detailed disassembly instructions
Constructor & Destructor Documentation
separationInfo_c() [1/3]
separationInfo_c::separationInfo_c (xmlParser_c & pars)
load separationInfo from parser
References xmlParser_c::END_TAG, xmlParser_c::exception(), xmlParser_c::getText(), xmlParser_c::next(), xmlParser_c::require(), xmlParser_c::START_TAG, xmlParser_c::TEXT, and values.
separationInfo_c() [2/3]
separationInfo_c::separationInfo_c (const separation_c * sep)
create a separation info from a normal separation
References recursiveConstruction().
separationInfo_c() [3/3]
separationInfo_c::separationInfo_c (const separationInfo_c &) private
Member Function Documentation
containsMultiMoves()
bool separationInfo_c::containsMultiMoves (unsigned int root) const private
used in movesText to find out if a branch has a move sequence longer than 1
References values.
Referenced by movesText2().
getNumSequences()
unsigned int separationInfo_c::getNumSequences (void) const virtual
helper function used for "compare" to get the number of move sequences
Implements disassembly_c.
References values.
getSequenceLength()
unsigned int separationInfo_c::getSequenceLength (unsigned int x) const virtual
helper function used for "compare" to get the number of moves for the x-th place in the string
Implements disassembly_c.
References values.
movesText()
virtual void separationInfo_c::movesText (char * txt, int len) const inline virtual
fill a string with dot separated numbers containing the moves required to disassemble the puzzle not more than len characters are written
Implements disassembly_c.
References movesText2().
movesText2()
int separationInfo_c::movesText2 (char * txt, int len, unsigned int idx) const private
References containsMultiMoves(), movesText2(), and values.
Referenced by movesText(), and movesText2().
operator=()
void separationInfo_c::operator= (const separationInfo_c &) private
recursiveConstruction()
void separationInfo_c::recursiveConstruction (const separation_c * sep) private
used in constructor for create separationInfo from normal separation
References separation_c::getLeft(), separation_c::getMoves(), separation_c::getRemoved(), recursiveConstruction(), and values.
Referenced by recursiveConstruction(), and separationInfo_c().
save()
void separationInfo_c::save (xmlWriter_c & xml) const
save into an xml node
References xmlWriter_c::addContent(), xmlWriter_c::endTag(), xmlWriter_c::newTag(), and values.
Referenced by solution_c::save().
sumMoves()
unsigned int separationInfo_c::sumMoves (void) const virtual
the number of moves to completely disassemble the puzzle, including all sub separations
Implements disassembly_c.
References values.
Member Data Documentation
values
std::vector<unsigned int> separationInfo_c::values private
this array contains the whole disassembly tree in prefix order, root, left, removed.
When a certain subtree is empty a zero is included, otherwise the number is the number of states within this tree node
example:
3 2 1 0 0 0 0     tree root 3 --> 2 --> 1
another example
3 1 1 0 0 0 1 1 0 0 0   tree root  3 --> 1 --> 1
                                    \--> 1 --> 1
Referenced by containsMultiMoves(), getNumSequences(), getSequenceLength(), movesText2(), recursiveConstruction(), save(), separationInfo_c(), and sumMoves().
The documentation for this class was generated from the following files:
src/lib/disassembly.h
src/lib/disassembly.cpp