BurrTools: mirrorInfo_c Class Reference
mirrorInfo_c Class Reference
this class contains mirror information for a given problem.
#include <assembly.h>
Classes
struct entry
structure containing mirror information for one piece pair
Public Member Functions
mirrorInfo_c (void)
void addPieces (unsigned int p1, unsigned int p2, unsigned char trans)
adds a pair of pieces that are mirrors or one another.
bool getPieceInfo (unsigned int p, unsigned int *p_out, unsigned char *trans) const
returns the piece information for piece p.
Private Member Functions
mirrorInfo_c (const mirrorInfo_c &)
void operator= (const mirrorInfo_c &)
Private Attributes
std::vector< entry > entries
the mirror pairs
Detailed Description
this class contains mirror information for a given problem.
this means it contains pairs of pieces that are mirror shapes of one another and how one piece is transformed into the other
Constructor & Destructor Documentation
mirrorInfo_c() [1/2]
mirrorInfo_c::mirrorInfo_c (void) inline
mirrorInfo_c() [2/2]
mirrorInfo_c::mirrorInfo_c (const mirrorInfo_c &) private
Member Function Documentation
addPieces()
void mirrorInfo_c::addPieces (unsigned int p1, unsigned int p2, unsigned char trans)
adds a pair of pieces that are mirrors or one another.
trans transforms the first piece into the 2nd
References entries, mirrorInfo_c::entry::pc1, mirrorInfo_c::entry::pc2, and mirrorInfo_c::entry::trans.
Referenced by assembler_1_c::prepare(), and assembler_0_c::prepare().
getPieceInfo()
bool mirrorInfo_c::getPieceInfo (unsigned int p, unsigned int * p_out, unsigned char * trans) const
returns the piece information for piece p.
p_out and trans contains the attached info returns only true, when valid entry was found
References entries.
Referenced by assembly_c::transform().
operator=()
void mirrorInfo_c::operator= (const mirrorInfo_c &) private
Member Data Documentation
entries
std::vector<entry> mirrorInfo_c::entries private
the mirror pairs
Referenced by addPieces(), and getPieceInfo().
The documentation for this class was generated from the following files:
src/lib/assembly.h
src/lib/assembly.cpp