BurrTools: puzzle_c Class Reference
puzzle_c Class Reference
This class defines the puzzle.
#include <puzzle.h>
Public Member Functions
puzzle_c (const puzzle_c *orig)
copy constructor this will NOT copy the labels and solutions of the problems.
puzzle_c (gridType_c *g)
Constructor for empty puzzle.
puzzle_c (xmlParser_c &pars)
load the puzzle from the XML file
void save (xmlWriter_c &xml) const
save the puzzle using the given XML-writer
~puzzle_c (void)
Destructor.
some functions to get the current set grid type for this puzzle
const gridType_c * getGridType (void) const
gridType_c * getGridType (void)
shape handling
unsigned int addShape (voxel_c *p)
Add the given shape to the puzzle.
unsigned int addShape (unsigned int sx, unsigned int sy, unsigned int sz)
add an empty shape of the given size return the index of the new shape
unsigned int getNumberOfShapes (void) const
return how many shapes there are in the puzzle
const voxel_c * getShape (unsigned int idx) const
get a shape
voxel_c * getShape (unsigned int idx)
get a shape
void removeShape (unsigned int idx)
remove the num-th shape.
void exchangeShapes (unsigned int s1, unsigned int s2)
exchange 2 shapes in the list of shapes.
handle puzzle colours
unsigned int addColor (unsigned char r, unsigned char g, unsigned char b)
add a colour, return the index of the new colour
void removeColor (unsigned int idx)
remove a colour with given index.
void changeColor (unsigned int idx, unsigned char r, unsigned char g, unsigned char b)
change the RGB value of one colour
void getColor (unsigned int idx, unsigned char *r, unsigned char *g, unsigned char *b) const
get the RGB value of one colour
unsigned int colorNumber (void) const
return the number of defined colours
handle problems
unsigned int addProblem (void)
add a new empty problem return its index
unsigned int addProblem (const problem_c *prob)
add a new problem as copy from another problem (from another puzzle).
unsigned int getNumberOfProblems (void) const
return the number of problems within this puzzle
void removeProblem (unsigned int p)
remove problem with the given index freeing all its resources
void exchangeProblems (unsigned int p1, unsigned int p2)
exchange problem at index p1 with problem at index p2
const problem_c * getProblem (unsigned int p) const
get the problem at index p
problem_c * getProblem (unsigned int p)
get the problem at index p
Private Attributes
gridType_c * gt
The gridtype of the puzzle.
std::vector< voxel_c * > shapes
The vector with the shapes.
std::vector< problem_c * > problems
the vector with the problems
std::vector< uint32_t > colors
The constraint colours.
std::string comment
some information about the puzzle no format is forced its free for the user
bool commentPopup
bool to signify if the comment should open on load.
the puzzle comment functions
void setComment (const std::string &com)
set comment there is no limitation in size or characters.
const std::string & getComment (void) const
get comment
bool getCommentPopup (void) const
find out if the comment popup flag is set
void setCommentPopup (bool val)
set or reset comment popup flag
puzzle_c (const puzzle_c &)
void operator= (const puzzle_c &)
Detailed Description
This class defines the puzzle.
A puzzle is a collection of shapes and a set of problems associated with these shapes and finally the colour used for colour constraint colours
Constructor & Destructor Documentation
puzzle_c() [1/4]
puzzle_c::puzzle_c (const puzzle_c * orig)
copy constructor this will NOT copy the labels and solutions of the problems.
References colors, comment, commentPopup, gridType_c::getVoxel(), gt, problems, and shapes.
puzzle_c() [2/4]
puzzle_c::puzzle_c (gridType_c * g) inline
Constructor for empty puzzle.
no shape, no problem and no colours ownership of the given gridtype is taken over, the memory is freed on destruction of this class
puzzle_c() [3/4]
puzzle_c::puzzle_c (xmlParser_c & pars)
load the puzzle from the XML file
References colors, comment, commentPopup, xmlParser_c::END_TAG, xmlParser_c::exception(), xmlParser_c::getAttributeCount(), xmlParser_c::getAttributeName(), xmlParser_c::getAttributeValue(), xmlParser_c::getName(), xmlParser_c::getText(), gridType_c::getVoxel(), gt, gridType_c::GT_BRICKS, xmlParser_c::next(), xmlParser_c::nextTag(), problems, xmlParser_c::require(), shapes, xmlParser_c::skipSubTree(), xmlParser_c::START_TAG, and xmlParser_c::TEXT.
~puzzle_c()
puzzle_c::~puzzle_c (void)
Destructor.
Deletes all the shapes and problems in the puzzle
References gt, problems, and shapes.
puzzle_c() [4/4]
puzzle_c::puzzle_c (const puzzle_c &) private
Member Function Documentation
addColor()
unsigned int puzzle_c::addColor (unsigned char r, unsigned char g, unsigned char b)
add a colour, return the index of the new colour
References bt_assert, and colors.
Referenced by doConvert().
addProblem() [1/2]
unsigned int puzzle_c::addProblem (const problem_c * prob)
add a new problem as copy from another problem (from another puzzle).
A copy of the provided problem is created
References problems.
addProblem() [2/2]
unsigned int puzzle_c::addProblem (void)
add a new empty problem return its index
similar functions for problems
References problems.
Referenced by doConvert(), and loadPuzzlerSolver3D().
addShape() [1/2]
unsigned int puzzle_c::addShape (unsigned int sx, unsigned int sy, unsigned int sz)
add an empty shape of the given size return the index of the new shape
References gridType_c::getVoxel(), gt, shapes, and voxel_c::VX_EMPTY.
addShape() [2/2]
unsigned int puzzle_c::addShape (voxel_c * p)
Add the given shape to the puzzle.
The space is taken over, and freed when the puzzle is destroyed Returns the index of the new shape
References bt_assert, voxel_c::getGridType(), gridType_c::getType(), gt, and shapes.
Referenced by doConvert(), and loadPuzzlerSolver3D().
changeColor()
void puzzle_c::changeColor (unsigned int idx, unsigned char r, unsigned char g, unsigned char b)
change the RGB value of one colour
References bt_assert, and colors.
colorNumber()
unsigned int puzzle_c::colorNumber (void) const inline
return the number of defined colours
References colors.
Referenced by problem_c::allowPlacement(), problem_c::disallowPlacement(), doConvert(), and problem_c::placementAllowed().
exchangeProblems()
void puzzle_c::exchangeProblems (unsigned int p1, unsigned int p2)
exchange problem at index p1 with problem at index p2
References bt_assert, and problems.
exchangeShapes()
void puzzle_c::exchangeShapes (unsigned int s1, unsigned int s2)
exchange 2 shapes in the list of shapes.
this function takes care to update all the problems and solutions because they only index into the shape list and exchanging shapes requires updating those indices
References bt_assert, exchangeShapes(), problems, and shapes.
Referenced by exchangeShapes().
getColor()
void puzzle_c::getColor (unsigned int idx, unsigned char * r, unsigned char * g, unsigned char * b) const
get the RGB value of one colour
References bt_assert, and colors.
Referenced by doConvert(), and removeColor().
getComment()
const std::string & puzzle_c::getComment (void) const inline
get comment
References comment.
Referenced by doConvert().
getCommentPopup()
bool puzzle_c::getCommentPopup (void) const inline
find out if the comment popup flag is set
References commentPopup.
Referenced by doConvert().
getGridType() [1/2]
gridType_c * puzzle_c::getGridType (void) inline
References gt.
getGridType() [2/2]
const gridType_c * puzzle_c::getGridType (void) const inline
References gt.
Referenced by assembly_c::createSpace(), doConvert(), assembler_0_c::getAssembly(), assembler_1_c::getAssembly(), movementAnalysator_c::movementAnalysator_c(), movementCache_c::movementCache_c(), assembler_1_c::prepare(), assembler_0_c::prepare(), print(), print(), problem_c::problem_c(), and solveThread_c::run().
getNumberOfProblems()
unsigned int puzzle_c::getNumberOfProblems (void) const inline
return the number of problems within this puzzle
References problems.
Referenced by doConvert(), and print().
getNumberOfShapes()
unsigned int puzzle_c::getNumberOfShapes (void) const inline
return how many shapes there are in the puzzle
References shapes.
Referenced by doConvert(), problem_c::getPartIdForShape(), problem_c::getResultId(), problem_c::getShapeMaximum(), problem_c::getShapeMinimum(), print(), problem_c::problem_c(), problem_c::resultValid(), problem_c::setResultId(), problem_c::setShapeMaximum(), and problem_c::setShapeMinimum().
getProblem() [1/2]
problem_c * puzzle_c::getProblem (unsigned int p) inline
get the problem at index p
References bt_assert, and problems.
getProblem() [2/2]
const problem_c * puzzle_c::getProblem (unsigned int p) const inline
get the problem at index p
References bt_assert, and problems.
Referenced by doConvert(), loadPuzzlerSolver3D(), and print().
getShape() [1/2]
voxel_c * puzzle_c::getShape (unsigned int idx) inline
get a shape
References bt_assert, and shapes.
getShape() [2/2]
const voxel_c * puzzle_c::getShape (unsigned int idx) const inline
get a shape
References bt_assert, and shapes.
Referenced by doConvert(), voxelTablePuzzle_c::findSpace(), problem_c::getPartShape(), problem_c::getPartShape(), getResultShape(), getResultShape(), loadPuzzlerSolver3D(), and print().
operator=()
void puzzle_c::operator= (const puzzle_c &) private
removeColor()
void puzzle_c::removeColor (unsigned int idx)
remove a colour with given index.
All shapes are updated to not use that colour any more, colour constraints are updated for all problems to no longer use that colour, its your task to make sure the now invalid solutions are removed
References bt_assert, colors, getColor(), problems, shapes, and voxel_c::VX_EMPTY.
removeProblem()
void puzzle_c::removeProblem (unsigned int p)
remove problem with the given index freeing all its resources
References bt_assert, and problems.
removeShape()
void puzzle_c::removeShape (unsigned int idx)
remove the num-th shape.
be careful this changes all ids and so all problems must be updated changing them, removing solutions, result shapes or pieces in problems...
References bt_assert, problems, removeShape(), and shapes.
Referenced by removeShape().
save()
void puzzle_c::save (xmlWriter_c & xml) const
save the puzzle using the given XML-writer
References xmlWriter_c::addContent(), colors, comment, commentPopup, xmlWriter_c::endTag(), gt, xmlWriter_c::newAttrib(), xmlWriter_c::newTag(), problems, gridType_c::save(), save(), and shapes.
Referenced by save().
setComment()
void puzzle_c::setComment (const std::string & com) inline
set comment there is no limitation in size or characters.
References comment.
Referenced by doConvert().
setCommentPopup()
void puzzle_c::setCommentPopup (bool val) inline
set or reset comment popup flag
References commentPopup.
Referenced by doConvert().
Member Data Documentation
colors
std::vector<uint32_t> puzzle_c::colors private
The constraint colours.
there can be many colours to constrain the placement of pieces these are the actual colours used to display them the red part is in the lowest 8 bit, followed by green and blue in the highest part
Referenced by addColor(), changeColor(), colorNumber(), getColor(), puzzle_c(), puzzle_c(), removeColor(), and save().
comment
std::string puzzle_c::comment private
some information about the puzzle no format is forced its free for the user
Referenced by getComment(), puzzle_c(), puzzle_c(), save(), and setComment().
commentPopup
bool puzzle_c::commentPopup private
bool to signify if the comment should open on load.
so when the gui loads a puzzle where this is true, it will always display the comment.
Referenced by getCommentPopup(), puzzle_c(), puzzle_c(), save(), and setCommentPopup().
gt
gridType_c* puzzle_c::gt private
The gridtype of the puzzle.
each puzzle has exactly one grid type, this is it normally it doesn't change, except if you convert a puzzle of one grid type into an other with a converter
Referenced by addShape(), addShape(), getGridType(), getGridType(), puzzle_c(), puzzle_c(), save(), and ~puzzle_c().
problems
std::vector<problem_c*> puzzle_c::problems private
the vector with the problems
Referenced by addProblem(), addProblem(), exchangeProblems(), exchangeShapes(), getNumberOfProblems(), getProblem(), getProblem(), puzzle_c(), puzzle_c(), removeColor(), removeProblem(), removeShape(), save(), and ~puzzle_c().
shapes
std::vector<voxel_c*> puzzle_c::shapes private
The vector with the shapes.
Referenced by addShape(), addShape(), exchangeShapes(), getNumberOfShapes(), getShape(), getShape(), puzzle_c(), puzzle_c(), removeColor(), removeShape(), save(), and ~puzzle_c().
The documentation for this class was generated from the following files:
src/lib/puzzle.h
src/lib/puzzle.cpp