BurrTools: disassembly_c Class Reference
disassembly_c Class Reference abstract
the disassembly is a common base class for the separation and separationInfo classes.
#include <disassembly.h>
Public Member Functions
disassembly_c (void)
virtual ~disassembly_c (void)
virtual unsigned int sumMoves (void) const =0
the number of moves to completely disassemble the puzzle, including all sub separations
virtual void movesText (char *txt, int len) const =0
fill a string with dot separated numbers containing the moves required to disassemble the puzzle not more than len characters are written
int compare (const disassembly_c *s2) const
compares this and the given separation, for a higher level.
Protected Member Functions
virtual unsigned int getSequenceLength (unsigned int x) const =0
helper function used for "compare" to get the number of moves for the x-th place in the string
virtual unsigned int getNumSequences (void) const =0
helper function used for "compare" to get the number of move sequences
Private Member Functions
disassembly_c (const disassembly_c &)
void operator= (const disassembly_c &)
Detailed Description
the disassembly is a common base class for the separation and separationInfo classes.
Constructor & Destructor Documentation
disassembly_c() [1/2]
disassembly_c::disassembly_c (void) inline
~disassembly_c()
virtual disassembly_c::~disassembly_c (void) inline virtual
disassembly_c() [2/2]
disassembly_c::disassembly_c (const disassembly_c &) private
Member Function Documentation
compare()
int disassembly_c::compare (const disassembly_c * s2) const
compares this and the given separation, for a higher level.
one separation is bigger than the other if all levels up to branch n are equal and on n+1 the level is larger then the level of the other if this assembly is bigger >0 is returned if this assembler is smaller <0 is returned if they are both equal =0 is returned
References getNumSequences(), and getSequenceLength().
Referenced by solveThread_c::assembly(), and comp_1_level().
getNumSequences()
virtual unsigned int disassembly_c::getNumSequences (void) const protected pure virtual
helper function used for "compare" to get the number of move sequences
Implemented in separation_c, and separationInfo_c.
Referenced by compare().
getSequenceLength()
virtual unsigned int disassembly_c::getSequenceLength (unsigned int x) const protected pure virtual
helper function used for "compare" to get the number of moves for the x-th place in the string
Implemented in separation_c, and separationInfo_c.
Referenced by compare().
movesText()
virtual void disassembly_c::movesText (char * txt, int len) const pure virtual
fill a string with dot separated numbers containing the moves required to disassemble the puzzle not more than len characters are written
Implemented in separation_c, and separationInfo_c.
operator=()
void disassembly_c::operator= (const disassembly_c &) private
sumMoves()
virtual unsigned int disassembly_c::sumMoves (void) const pure virtual
the number of moves to completely disassemble the puzzle, including all sub separations
Implemented in separation_c, and separationInfo_c.
Referenced by solveThread_c::assembly(), and comp_2_moves().
The documentation for this class was generated from the following files:
src/lib/disassembly.h
src/lib/disassembly.cpp