BurrTools: solution_c Class Reference
solution_c Class Reference
This class stores the information for one solution for a problem.
#include <solution.h>
Public Member Functions
solution_c (assembly_c *assm, unsigned int assmNum, separation_c *t, unsigned int solNum)
create a solution with a proper separation
solution_c (assembly_c *assm, unsigned int assmNum, separationInfo_c *ti, unsigned int solNum)
create a solution with only separation information
solution_c (assembly_c *assm, unsigned int assmNum)
create a solution with assembly only, no disassembly
solution_c (xmlParser_c &pars, unsigned int pieces, const gridType_c *gt)
load a solution from file
~solution_c (void)
void save (xmlWriter_c &xml) const
save the solution to the XML file
assembly_c * getAssembly (void)
get the assembly from this solution, it will always be not NULL
const assembly_c * getAssembly (void) const
separation_c * getDisassembly (void)
get the full disassembly or 0 if there is none
const separation_c * getDisassembly (void) const
disassembly_c * getDisassemblyInfo (void)
get either the disassembly or the disassembly information or nothing
const disassembly_c * getDisassemblyInfo (void) const
unsigned int getAssemblyNumber (void) const
get the assembly number
unsigned int getSolutionNumber (void) const
get the solution number (0 if this solution has no disassembly
void removeDisassembly (void)
remove an existing disassembly, and replace it by disassembly information
void setDisassembly (separation_c *sep)
add a new disassembly to this solution, deleting an old one, in case such an old exists
void exchangeShape (unsigned int s1, unsigned int s2)
change the solution so that shape s1 and s2 are swapped
void removePieces (unsigned int start, unsigned int count)
remove count pieces starting with start from all information within this solution
void addNonPlacedPieces (unsigned int start, unsigned int count)
add count not placed pieces starting at position start
Private Attributes
assembly_c * assembly
separation_c * tree
separationInfo_c * treeInfo
unsigned int assemblyNum
unsigned int solutionNum
Detailed Description
This class stores the information for one solution for a problem.
Constructor & Destructor Documentation
solution_c() [1/4]
solution_c::solution_c (assembly_c * assm, unsigned int assmNum, separation_c * t, unsigned int solNum) inline
create a solution with a proper separation
solution_c() [2/4]
solution_c::solution_c (assembly_c * assm, unsigned int assmNum, separationInfo_c * ti, unsigned int solNum) inline
create a solution with only separation information
solution_c() [3/4]
solution_c::solution_c (assembly_c * assm, unsigned int assmNum) inline
create a solution with assembly only, no disassembly
solution_c() [4/4]
solution_c::solution_c (xmlParser_c & pars, unsigned int pieces, const gridType_c * gt)
load a solution from file
References assembly, assemblyNum, xmlParser_c::END_TAG, xmlParser_c::exception(), xmlParser_c::getAttributeValue(), xmlParser_c::getName(), assembly_c::isPlaced(), xmlParser_c::nextTag(), assembly_c::placementCount(), xmlParser_c::require(), xmlParser_c::skipSubTree(), solutionNum, xmlParser_c::START_TAG, tree, and treeInfo.
~solution_c()
solution_c::~solution_c (void)
References assembly, tree, and treeInfo.
Member Function Documentation
addNonPlacedPieces()
void solution_c::addNonPlacedPieces (unsigned int start, unsigned int count)
add count not placed pieces starting at position start
References assembly_c::addNonPlacedPieces(), separation_c::addNonPlacedPieces(), assembly, and tree.
exchangeShape()
void solution_c::exchangeShape (unsigned int s1, unsigned int s2)
change the solution so that shape s1 and s2 are swapped
References assembly, assembly_c::exchangeShape(), separation_c::exchangeShape(), and tree.
getAssembly() [1/2]
assembly_c * solution_c::getAssembly (void) inline
get the assembly from this solution, it will always be not NULL
References assembly.
Referenced by comp_3_pieces().
getAssembly() [2/2]
const assembly_c * solution_c::getAssembly (void) const inline
References assembly.
getAssemblyNumber()
unsigned int solution_c::getAssemblyNumber (void) const inline
get the assembly number
References assemblyNum.
Referenced by comp_0_assembly().
getDisassembly() [1/2]
separation_c * solution_c::getDisassembly (void) inline
get the full disassembly or 0 if there is none
References tree.
Referenced by solveThread_c::assembly().
getDisassembly() [2/2]
const separation_c * solution_c::getDisassembly (void) const inline
References tree.
getDisassemblyInfo() [1/2]
disassembly_c * solution_c::getDisassemblyInfo (void)
get either the disassembly or the disassembly information or nothing
References tree, and treeInfo.
Referenced by solveThread_c::assembly(), comp_1_level(), and comp_2_moves().
getDisassemblyInfo() [2/2]
const disassembly_c * solution_c::getDisassemblyInfo (void) const
References tree, and treeInfo.
getSolutionNumber()
unsigned int solution_c::getSolutionNumber (void) const inline
get the solution number (0 if this solution has no disassembly
References solutionNum.
removeDisassembly()
void solution_c::removeDisassembly (void)
remove an existing disassembly, and replace it by disassembly information
References tree, and treeInfo.
removePieces()
void solution_c::removePieces (unsigned int start, unsigned int count)
remove count pieces starting with start from all information within this solution
References assembly, assembly_c::removePieces(), separation_c::removePieces(), and tree.
save()
void solution_c::save (xmlWriter_c & xml) const
save the solution to the XML file
References assembly, assemblyNum, xmlWriter_c::endTag(), xmlWriter_c::newAttrib(), xmlWriter_c::newTag(), assembly_c::save(), separationInfo_c::save(), separation_c::save(), solutionNum, tree, and treeInfo.
setDisassembly()
void solution_c::setDisassembly (separation_c * sep)
add a new disassembly to this solution, deleting an old one, in case such an old exists
References tree, and treeInfo.
Member Data Documentation
assembly
assembly_c* solution_c::assembly private
Referenced by addNonPlacedPieces(), exchangeShape(), getAssembly(), getAssembly(), removePieces(), save(), solution_c(), and ~solution_c().
assemblyNum
unsigned int solution_c::assemblyNum private
Referenced by getAssemblyNumber(), save(), and solution_c().
solutionNum
unsigned int solution_c::solutionNum private
Referenced by getSolutionNumber(), save(), and solution_c().
tree
separation_c* solution_c::tree private
Referenced by addNonPlacedPieces(), exchangeShape(), getDisassembly(), getDisassembly(), getDisassemblyInfo(), getDisassemblyInfo(), removeDisassembly(), removePieces(), save(), setDisassembly(), solution_c(), and ~solution_c().
treeInfo
separationInfo_c* solution_c::treeInfo private
Referenced by getDisassemblyInfo(), getDisassemblyInfo(), removeDisassembly(), save(), setDisassembly(), solution_c(), and ~solution_c().
The documentation for this class was generated from the following files:
src/lib/solution.h
src/lib/solution.cpp