BurrTools: thread_c Class Reference
thread_c Class Reference abstract
#include <thread.h>
Public Member Functions
thread_c (void)
create the thread data structure, but don't start the thread
virtual ~thread_c (void)
kill the thread and then delete data structure
bool start ()
run the thread return true on success
virtual void stop ()
inform the thread to stop running, this is dependent on the thread
void kill ()
kill the thread
bool isRunning (void)
return true, if the thread is running
Protected Member Functions
virtual void run (void)=0
this is the function that gets started for the thread, once this function finishes, the thread will end
Private Member Functions
void start_thread (void)
thread_c (const thread_c &)
void operator= (const thread_c &)
Private Attributes
boost::thread thread
bool running
Constructor & Destructor Documentation
thread_c() [1/2]
thread_c::thread_c (void) inline
create the thread data structure, but don't start the thread
~thread_c()
thread_c::~thread_c (void) virtual
kill the thread and then delete data structure
References kill().
thread_c() [2/2]
thread_c::thread_c (const thread_c &) private
Member Function Documentation
isRunning()
bool thread_c::isRunning (void) inline
return true, if the thread is running
References running.
kill()
void thread_c::kill ()
kill the thread
References stop(), and thread.
Referenced by solveThread_c::~solveThread_c(), and ~thread_c().
operator=()
void thread_c::operator= (const thread_c &) private
run()
virtual void thread_c::run (void) protected pure virtual
this is the function that gets started for the thread, once this function finishes, the thread will end
Implemented in solveThread_c.
Referenced by start_thread().
start()
bool thread_c::start ()
run the thread return true on success
References running, start_thread(), and thread.
Referenced by solveThread_c::start().
start_thread()
void thread_c::start_thread (void) private
References run(), and running.
Referenced by start().
stop()
virtual void thread_c::stop (void) inline virtual
inform the thread to stop running, this is dependent on the thread
Reimplemented in solveThread_c.
Referenced by kill().
Member Data Documentation
running
bool thread_c::running private
Referenced by isRunning(), start(), and start_thread().
thread
boost::thread thread_c::thread private
Referenced by kill(), and start().
The documentation for this class was generated from the following files:
src/lib/thread.h
src/lib/thread.cpp