BurrTools: voxel_3_c Class Reference
voxel_3_c Class Reference
Voxel class for the rhombic grid.
#include <voxel_3.h>
Public Member Functions
voxel_3_c (unsigned int x, unsigned int y, unsigned int z, const gridType_c *gt, voxel_type init=0)
voxel_3_c (xmlParser_c &pars, const gridType_c *gt)
voxel_3_c (const voxel_c &orig)
voxel_3_c (const voxel_c *orig)
virtual bool transform (unsigned int nr)
the transformation function for cubic grids
bool getNeighbor (unsigned int idx, unsigned int typ, int x, int y, int z, int *xn, int *yn, int *zn) const
returns the coordinates for a neighbour to the given voxel
void scale (unsigned int amount, bool grid)
scale the space, making x by x by x cubes out of single cubes
bool scaleDown (unsigned char by, bool action)
Scale down voxel space by a certain amount.
void resizeInclude (int &px, int &py, int &pz)
resizes and translates the space so that the the given voxel can be included the function returns the new coordinate of the point.
void minimizePiece (void)
changes the size of the voxel space to the smallest size so that all voxels whose value is not 0 can be contained.
virtual bool validCoordinate (int x, int y, int z) const
Return if a given coordinate is valid to use.
bool identicalInBB (const voxel_c *op, bool includeColors=true) const
Comparison of two voxel spaces.
bool onGrid (int x, int y, int z) const
this function is used to find out if the given position is of the same voxel type as the voxel at position 0.
virtual bool meshParamsValid (double bevel, double offset) const
void getConnectionFace (int x, int y, int z, int n, double bevel, double offset, std::vector< float > &faceCorners) const
this function must return a polygon that is the connecting face to the neighbour n for the voxel at position x, y, z The function is used by the default implementation of getMesh to generate the default basis mesh it is also used by the 3D cursor drawing code
void calculateSize (float *x, float *y, float *z) const
calculate the size, that the returned mesh has
void recalcSpaceCoordinates (float *x, float *y, float *z) const
Public Member Functions inherited from voxel_0_c
voxel_0_c (unsigned int x, unsigned int y, unsigned int z, const gridType_c *gt, voxel_type init=0)
voxel_0_c (xmlParser_c &pars, const gridType_c *gt)
voxel_0_c (const voxel_c &orig)
voxel_0_c (const voxel_c *orig)
void transformPoint (int *x, int *y, int *z, unsigned int trans) const
this function transforms the given point by the given transformation around the origin
Public Member Functions inherited from voxel_c
void skipRecalcBoundingBox (bool skipit)
enable or disable the update of the bounding box after each operation.
voxel_c (unsigned int x, unsigned int y, unsigned int z, const gridType_c *gt, voxel_type init=0)
Creates a new voxel space.
voxel_c (xmlParser_c &pars, const gridType_c *gt)
Load a voxel space from xml node.
voxel_c (const voxel_c &orig)
Copy constructor using reference.
voxel_c (const voxel_c *orig)
Copy constructor using pointer.
virtual ~voxel_c ()
Destructor.
void copy (const voxel_c *orig)
make this voxelspace be identical to the one given.
unsigned int getX (void) const
Return x-size of the voxel space.
unsigned int getY (void) const
Return y-size of the voxel space.
unsigned int getZ (void) const
Return z-size of the voxel space.
const gridType_c * getGridType (void) const
get the gridtype of this voxel space
unsigned int getDiagonal (void) const
Returns the squared diagonal of the space.
unsigned int getBiggestDimension (void) const
Returns the value of the biggest out of getX, getY or getZ.
unsigned int getXYZ (void) const
Get the number of voxels, which is getX()*getY()*getZ()
int getIndex (unsigned int x, unsigned int y, unsigned int z) const
This function returns the index for a given triple of x, y and z.
bool indexToXYZ (unsigned int index, unsigned int *x, unsigned int *y, unsigned int *z) const
The inverse of getIndex.
voxel_type get (unsigned int x, unsigned int y, unsigned int z) const
Get the value of the voxel at position .
voxel_type get2 (int x, int y, int z) const
same as get but returns VX_EMPTY for each voxel outside the space
voxel_type get (unsigned int p) const
Get voxel by index.
bool neighbour (unsigned int p, voxel_type val) const
returns true, if a neighbour of the given voxel has the given value
void set (unsigned int x, unsigned int y, unsigned int z, voxel_type val)
the x, y, z variant of the set function.
void set (unsigned int p, voxel_type val)
The 1-dimensional variant of the set function.
void setAll (voxel_type val)
Set all the voxels to the given value.
unsigned int count (voxel_type val) const
counts the number of voxels that have the given value
void translate (int dx, int dy, int dz, voxel_type filler)
shift the space around.
unsigned int boundX1 (void) const
Get the coordinate of the Bounding Box.
unsigned int boundX2 (void) const
Get the coordinate of the Bounding Box.
unsigned int boundY1 (void) const
Get the coordinate of the Bounding Box.
unsigned int boundY2 (void) const
Get the coordinate of the Bounding Box.
unsigned int boundZ1 (void) const
Get the coordinate of the Bounding Box.
unsigned int boundZ2 (void) const
Get the coordinate of the Bounding Box.
bool getBoundingBox (unsigned char trans, int *x1, int *y1, int *z1, int *x2=0, int *y2=0, int *z2=0) const
get the bounding box of a rotated voxel space
bool operator== (const voxel_c &op) const
Comparison of two voxel spaces.
bool identicalWithRots (const voxel_c *op, bool includeMirror, bool includeColors) const
comparison of 2 voxel spaces.
unsigned char getMirrorTransform (const voxel_c *op) const
this function returns the transformation, that transforms this voxel space into the as parameter given one
void resize (unsigned int nsx, unsigned int nsy, unsigned int nsz, voxel_type filler)
resizes the voxelspace.
bool connected (char type, bool inverse, voxel_type value, bool outsideZ=true) const
checks the voxelspace for connectedness.
void fillHoles (char type)
fills in all empty voxels that are completely surrounded by non empty voxels,
symmetries_t selfSymmetries (void) const
This function returns the self symmetries of this voxel space.
unsigned char normalizeTransformation (unsigned char trans) const
this function returns the smallest transformation number that results in an identical shape for this voxel space
int getState (unsigned int x, unsigned int y, unsigned int z) const
Functions to get the voxel state or color of a single voxel.
int getState2 (int x, int y, int z) const
int getState (unsigned int i) const
unsigned int getColor (unsigned int x, unsigned int y, unsigned int z) const
unsigned int getColor2 (int x, int y, int z) const
unsigned int getColor (unsigned int i) const
bool isEmpty (unsigned int x, unsigned int y, unsigned int z) const
Functions to ask, if a voxel has a certain state.
bool isEmpty2 (int x, int y, int z) const
bool isEmpty (unsigned int i) const
bool isFilled (unsigned int x, unsigned int y, unsigned int z) const
bool isFilled2 (int x, int y, int z) const
bool isFilled (unsigned int i) const
bool isVariable (unsigned int x, unsigned int y, unsigned int z) const
bool isVariable2 (int x, int y, int z) const
bool isVariable (unsigned int i) const
void setState (unsigned int x, unsigned int y, unsigned int z, int state)
Functions to set the state or colour of a certain voxel.
void setColor (unsigned int x, unsigned int y, unsigned int z, unsigned int color)
void setState (unsigned int i, int state)
void setColor (unsigned int i, unsigned int color)
unsigned int countState (int state) const
Counts how many voxels there are of a certain state.
void actionOnSpace (VoxelAction action, bool inside)
Change the state of some or all voxels.
void save (xmlWriter_c &xml) const
used to save to XML
int getHx (void) const
Get the hotspot.
int getHy (void) const
Get the hotspot.
int getHz (void) const
Get the hotspot.
void setHotspot (int x, int y, int z)
Set the hotspot.
virtual void initHotspot (void)
Initialise the hotspot to a valid position.
bool getHotspot (unsigned char trans, int *x, int *y, int *z) const
this function returns the hotspot of the rotated space.
const std::string & getName (void) const
function to get the name
void setName (const std::string &n)
Set the name for this voxel space.
int getWeight (void) const
get the weight of this space
void setWeight (int w)
set the weight of this space
bool unionintersect (const voxel_c *va, int xa, int ya, int za, const voxel_c *vb, int xb, int yb, int zb)
virtual Polyhedron * getMesh (double bevel, double offset) const
this function returns a polyhedron mesh of this shape.
virtual Polyhedron * getDrawingMesh (void) const
returns the drawing mesh.
virtual Polyhedron * getWireframeMesh (void) const
returns the drawing mesh for wire-frame mode.
Private Member Functions
void operator= (const voxel_3_c &)
Additional Inherited Members
Public Types inherited from voxel_c
enum VoxelState { VX_EMPTY , VX_FILLED , VX_VARIABLE }
this enumeration defines some values that are used for some of the voxel spaces.
enum VoxelAction { ACT_FIXED , ACT_VARIABLE , ACT_DECOLOR }
Defined possible actions for the actionOnSpace function.
Protected Member Functions inherited from voxel_c
void recalcBoundingBox (void)
updates the bounding box to fit the current shape inside the space.
virtual Polyhedron * getMeshInternal (double bevel, double offset, bool fast) const
Protected Attributes inherited from voxel_c
const gridType_c * gt
each voxel needs to know the parameters for its space grid
unsigned int sx
The x size of the space.
unsigned int sy
The y size of the space.
unsigned int sz
The z size of the space.
unsigned int voxels
The number of voxel inside the space.
voxel_type * space
The space.
unsigned int bx1
lower x-coordinate of the Bounding Box
unsigned int bx2
upper x-coordinate of the Bounding Box
unsigned int by1
lower y-coordinate of the Bounding Box
unsigned int by2
upper y-coordinate of the Bounding Box
unsigned int bz1
lower z-coordinate of the Bounding Box
unsigned int bz2
upper z-coordinate of the Bounding Box
bool doRecalc
bounding box recalculation is only done when this is true
symmetries_t symmetries
the self symmetries of this voxel space.
int hx
x-coordinate of The Hot Spot
int hy
y-coordinate of The Hot Spot
int hz
z-coordinate of The Hot Spot
std::string name
The name of the shape.
int weight
Weight of the shape.
int * BbHsCache
A cache for hotspot and bounding box coordinates of the rotated voxel.
Detailed Description
Voxel class for the rhombic grid.
This grid builds on top of the cube grid. The rhombic grid is emulated using cubes. So this class uses many functions from the cubes voxel space.
This class mainly adds alignment functionality for transformations and the neighbour functionality.
The rhombic grid emulation is explained in the user guide with some graphics, here I can place only a textual description which might be hard to understand.
It is possible to halve a cube in such a way that you get 2 prisms with a triangle as base face. This triangle has a shape of an rectangular triangle with sides of length 1, 1 and sqrt(2). There are 2*3 = 6 such cuts possible. If you do all those 6 cuts on a cube you get 24 little irregular but identical tetrahedras. Those are the building blocks of the rhombic grid.
The cube with its 24 tetrahedras is emulated in a 5x5x5 sized cube within the cubic grid. The 24 tetrahedras are located as little diamonds on each of the six faces of the 5x5x5 cube. That makes 6 faces with 4 cubes each = 24 voxels.
Have a look at the user guide to see this and play with BurrTools to understand the grid.
With this grid it is possible to build rhombic dodecahedrons. The grid needs alignment of 5 in each direction to ensure voxels don't change parity when the shape is rotated. Also translations can only be done in multiples of 5 and so on...
Constructor & Destructor Documentation
voxel_3_c() [1/4]
voxel_3_c::voxel_3_c (unsigned int x, unsigned int y, unsigned int z, const gridType_c * gt, voxel_type init = 0) inline
voxel_3_c() [2/4]
voxel_3_c::voxel_3_c (xmlParser_c & pars, const gridType_c * gt) inline
voxel_3_c() [3/4]
voxel_3_c::voxel_3_c (const voxel_c & orig) inline
voxel_3_c() [4/4]
voxel_3_c::voxel_3_c (const voxel_c * orig) inline
Member Function Documentation
calculateSize()
void voxel_3_c::calculateSize (float * x, float * y, float * z) const virtual
calculate the size, that the returned mesh has
Reimplemented from voxel_0_c.
References voxel_c::getX(), voxel_c::getY(), and voxel_c::getZ().
getConnectionFace()
void voxel_3_c::getConnectionFace (int , int , int , int , double , double , std::vector< float > &) const virtual
this function must return a polygon that is the connecting face to the neighbour n for the voxel at position x, y, z The function is used by the default implementation of getMesh to generate the default basis mesh it is also used by the 3D cursor drawing code
Reimplemented from voxel_0_c.
References bt_assert, intdiv_inf(), and voxel_c::voxels.
getNeighbor()
bool voxel_3_c::getNeighbor (unsigned int idx, unsigned int typ, int x, int y, int z, int * xn, int * yn, int * zn) const virtual
returns the coordinates for a neighbour to the given voxel
idx is the index if the neighbour, if you want the next neighbour, give the next number typ is what kind of neighbour you want, face (0), edge (1) or corner (2) x, y, z coordinate for the source xn, yn, zn, coordinate for the neighbour return true, when a valid neighbour with that index exists
This function is different for different grids. There is no default implementation, so each grid has to define its own version of this function
Reimplemented from voxel_0_c.
References coordinateToggling(), and intdiv_inf().
identicalInBB()
bool voxel_3_c::identicalInBB (const voxel_c * op, bool includeColors = true) const virtual
Comparison of two voxel spaces.
2 voxel spaces are identical, if their bounding boxes have the same size and the voxels within there boxes is identical
if includeColors is true, the colours are included in the comparison, meaning when the colours differ the shapes are not equal, otherwise only the states are compared
There are special conditions to take care in different grid (e.g alignment along a bigger grid) so this function can be overloaded. The default implementation simply treats all voxels equal
Reimplemented from voxel_c.
References voxel_c::boundX1(), voxel_c::boundY1(), voxel_c::boundZ1(), voxel_c::bx1, voxel_c::by1, voxel_c::bz1, and voxel_c::identicalInBB().
meshParamsValid()
bool voxel_3_c::meshParamsValid (double bevel, double offset) const virtual
Reimplemented from voxel_0_c.
minimizePiece()
void voxel_3_c::minimizePiece (void) virtual
changes the size of the voxel space to the smallest size so that all voxels whose value is not 0 can be contained.
as in some grids there are special conditions to consider when doing this operation the function can be overloaded. This default implementation will minimise to the bounding box.
Reimplemented from voxel_c.
References voxel_c::bx1, voxel_c::by1, voxel_c::bz1, voxel_c::minimizePiece(), voxel_c::resize(), voxel_c::sx, voxel_c::sy, voxel_c::sz, and voxel_c::translate().
onGrid()
bool voxel_3_c::onGrid (int x, int y, int z) const virtual
this function is used to find out if the given position is of the same voxel type as the voxel at position 0.
This is used to find out if a piece can be placed at a certain position in a voxel grid
Reimplemented from voxel_0_c.
operator=()
void voxel_3_c::operator= (const voxel_3_c &) private
recalcSpaceCoordinates()
void voxel_3_c::recalcSpaceCoordinates (float * x, float * y, float * z) const virtual
Reimplemented from voxel_c.
resizeInclude()
void voxel_3_c::resizeInclude (int & px, int & py, int & pz) virtual
resizes and translates the space so that the the given voxel can be included the function returns the new coordinate of the point.
Each grid has to implement it's own version because there are different kinds of supergrids that are imposed on the normal grid
Reimplemented from voxel_0_c.
References voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), voxel_c::resize(), and voxel_c::translate().
scale()
void voxel_3_c::scale (unsigned int amount, bool grid) virtual
scale the space, making x by x by x cubes out of single cubes
This must be done differently by all grids. The default implementation doesn't do anything. It's just there to allow grids without scaling as not all grid have such a possibility (e.g. spheres can't be scaled) if grid is true (not all functions need to support this) the result it not filled, but rather a grid with only the outer edges filled
Reimplemented from voxel_0_c.
References voxel_c::count(), voxel_c::get(), voxel_c::hx, voxel_c::hy, voxel_c::hz, voxel_c::isEmpty2(), voxel_c::recalcBoundingBox(), voxel_c::space, voxel_c::sx, voxel_c::sy, voxel_c::sz, voxel_c::voxels, and voxel_c::VX_EMPTY.
scaleDown()
bool voxel_3_c::scaleDown (unsigned char by, bool action) virtual
Scale down voxel space by a certain amount.
for the minimise scale function applied to all shapes we need to first check, if all shapes can be scaled down by a certain factor and then do it. If action is true, then the shape is really scaled, otherwise you only get the fact if it is scalable by the given amount
This must be done differently by all grids. The default implementation doesn't do anything. It's just there to allow grids without scaling as not all grid have such a possibility (e.g. spheres can't be scaled)
Reimplemented from voxel_0_c.
transform()
bool voxel_3_c::transform (unsigned int nr) virtual
the transformation function for cubic grids
The nice thing about the cubic grid is that we can easily calculate how big the grid will be after the transformation, we can also easily calculate the new bounding box and the now position for the hotspot.
This makes this transformation function faster than the other 2 variations for spheres and triangles
Reimplemented from voxel_0_c.
References voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), voxel_c::resize(), voxel_c::sx, voxel_c::sy, voxel_c::sz, and voxel_0_c::transform().
validCoordinate()
bool voxel_3_c::validCoordinate (int x, int y, int z) const virtual
Return if a given coordinate is valid to use.
In some voxel spaces not all possible coordinates are valid. For example in the sphere grid only the coordinates with (x+y+z) % 2 == 0 are valid This function does that calculation
Reimplemented from voxel_0_c.
The documentation for this class was generated from the following files:
src/lib/voxel_3.h
src/lib/voxel_3.cpp