BurrTools: xmlParser_c Class Reference
xmlParser_c Class Reference
A simple, pull based XML parser.
#include <xml.h>
Public Types
enum {
START_DOCUMENT , END_DOCUMENT , START_TAG , END_TAG ,
TEXT , CDSECT , ENTITY_REF , IGNORABLE_WHITESPACE ,
PROCESSING_INSTRUCTION , COMMENT , DOCDECL , UNKNOWN
}
possible xml events
Public Member Functions
xmlParser_c (std::istream &is)
xmlParser_c (void)
~xmlParser_c (void)
std::string getInputEncoding (void)
void defineEntityReplacementText (std::string entity, std::string value)
int getDepth (void)
std::string getPositionDescription (void)
bool isWhitespace (void)
std::string getText (void)
return the text of the current text node.
const char * getTextCharacters (int *poslen)
std::string getName (void)
get the name of the current tag
std::string getPrefix (void)
bool isEmptyElementTag (void)
int getAttributeCount (void)
get the number of attributes in the current tag
std::string getAttributeName (int index)
get the name of one of the attributes
std::string getAttributePrefix (int index)
std::string getAttributeValue (int index)
get the value of one of the attributes
std::string getAttributeValue (std::string name)
get the value of the given attribut.
int getEventType (void)
int next (void)
go to the next xml event, and return the event type
int nextToken (void)
int nextTag (void)
void prevTag (void)
void require (int type, std::string name)
check, if the parser is in a certain state.
std::string nextText (void)
void skipSubTree (void)
skip the complete tree until the close of the current tag.
void exception (std::string desc)
throws XmlPullParserException with the current line and col.
Private Member Functions
void commonInit (void)
void initBuf (void)
std::string state (int eventType)
std::string * ensureCapacity (std::string *arr, int required)
void nextImpl ()
common base for next and nextToken.
int parseLegacy (bool push)
void parseDoctype (bool push)
precondition: &lt! consumed
void parseEndTag ()
int peekType ()
std::string get (int pos)
void push (int c)
void parseStartTag (bool xmldecl)
Sets name and attributes.
void pushEntity ()
result: isWspace; if the setName parameter is set, the name of the entity is stored in "name"
void pushText (int delimiter, bool resolveEntities)
types: '<': parse to any token (for nextToken ()) '"': parse to quote ' ': parse to whitespace or '>'
void read (char c)
int read ()
int peekbuf (int pos)
Does never read more than needed.
std::string readName ()
void skip ()
Private Attributes
std::string unexpected_eof
std::string illegal_type
int LEGACY
int XML_DECL
std::string version
bool standalone
bool processNsp
bool relaxed
std::map< std::string, std::string > entityMap
int depth
std::vector< std::string > nspStack
std::vector< std::string > elementStack
int * nspCounts
int nspSize
std::string encoding
char * srcBuf
int srcPos
int srcCount
int srcBuflength
int line
int column
char * txtBuf
int txtPos
int txtBufSize
int type
std::string text
bool isWspace
bool skipNextTag
std::string Ns
std::string prefix
std::string name
bool degenerated
int attributeCount
std::vector< std::string > attributes
std::istream & reader
int peek [2]
A separate peek buffer seems simpler than managing wrap around in the first level read buffer.
int peekCount
bool wasCR
bool unresolved
bool token
Detailed Description
A simple, pull based XML parser.
As this parser is taken from an other project I don't understand it completely I only comment the functions that I used...
Member Enumeration Documentation
anonymous enum
anonymous enum
possible xml events
Enumerator
START_DOCUMENT
END_DOCUMENT
START_TAG
an open tag (can be both tag types)
END_TAG
the end of a node (either closing tag, or short tag)
TEXT
a text node
CDSECT
ENTITY_REF
IGNORABLE_WHITESPACE
PROCESSING_INSTRUCTION
COMMENT
DOCDECL
UNKNOWN
Constructor & Destructor Documentation
xmlParser_c() [1/2]
xmlParser_c::xmlParser_c (std::istream & is)
References commonInit(), and initBuf().
xmlParser_c() [2/2]
xmlParser_c::xmlParser_c (void)
References commonInit(), and initBuf().
~xmlParser_c()
xmlParser_c::~xmlParser_c (void)
References nspCounts, srcBuf, and txtBuf.
Member Function Documentation
commonInit()
void xmlParser_c::commonInit (void) private
References attributeCount, column, degenerated, depth, encoding, entityMap, LEGACY, line, name, Ns, nspCounts, nspSize, peekCount, relaxed, skipNextTag, srcCount, srcPos, standalone, START_DOCUMENT, type, unresolved, version, and XML_DECL.
Referenced by xmlParser_c(), and xmlParser_c().
defineEntityReplacementText()
void xmlParser_c::defineEntityReplacementText (std::string entity, std::string value)
References entityMap, and exception().
ensureCapacity()
std::string * xmlParser_c::ensureCapacity (std::string * arr, int required) private
exception()
void xmlParser_c::exception (std::string desc)
throws XmlPullParserException with the current line and col.
You may use this, if you have encounteted a faulty XML, e.g missing attribute or what not.
References column, line, state(), and type.
Referenced by assembly_c::assembly_c(), defineEntityReplacementText(), getAttributeName(), getAttributePrefix(), getAttributeValue(), gridType_c::gridType_c(), isEmptyElementTag(), isWhitespace(), nextTag(), nextText(), parseDoctype(), parseEndTag(), parseLegacy(), parseStartTag(), problem_c::problem_c(), pushEntity(), puzzle_c::puzzle_c(), read(), readName(), require(), separation_c::separation_c(), separationInfo_c::separationInfo_c(), solution_c::solution_c(), state_c::state_c(), and voxel_c::voxel_c().
get()
std::string xmlParser_c::get (int pos) private
References txtBuf, and txtPos.
Referenced by getText(), parseStartTag(), pushEntity(), and readName().
getAttributeCount()
int xmlParser_c::getAttributeCount (void) inline
get the number of attributes in the current tag
References attributeCount.
Referenced by puzzle_c::puzzle_c().
getAttributeName()
std::string xmlParser_c::getAttributeName (int index)
get the name of one of the attributes
References attributeCount, attributes, and exception().
Referenced by parseStartTag(), and puzzle_c::puzzle_c().
getAttributePrefix()
std::string xmlParser_c::getAttributePrefix (int index)
References attributeCount, attributes, and exception().
getAttributeValue() [1/2]
std::string xmlParser_c::getAttributeValue (int index)
get the value of one of the attributes
References attributeCount, attributes, and exception().
Referenced by gridType_c::gridType_c(), problem_c::problem_c(), puzzle_c::puzzle_c(), separation_c::separation_c(), solution_c::solution_c(), and voxel_c::voxel_c().
getAttributeValue() [2/2]
std::string xmlParser_c::getAttributeValue (std::string name)
get the value of the given attribut.
If the attribut doesn't exist an empty string is returned
References attributeCount, and attributes.
getDepth()
int xmlParser_c::getDepth (void)
References depth.
getEventType()
int xmlParser_c::getEventType (void) inline
References type.
getInputEncoding()
std::string xmlParser_c::getInputEncoding (void)
References encoding.
getName()
std::string xmlParser_c::getName (void) inline
get the name of the current tag
References name.
Referenced by problem_c::problem_c(), puzzle_c::puzzle_c(), require(), separation_c::separation_c(), solution_c::solution_c(), and state_c::state_c().
getPositionDescription()
std::string xmlParser_c::getPositionDescription (void)
getPrefix()
std::string xmlParser_c::getPrefix (void) inline
References prefix.
getText()
std::string xmlParser_c::getText (void)
return the text of the current text node.
Only call when you are actually in a text node.
References ENTITY_REF, get(), TEXT, type, and unresolved.
Referenced by assembly_c::assembly_c(), nextText(), problem_c::problem_c(), puzzle_c::puzzle_c(), separation_c::separation_c(), separationInfo_c::separationInfo_c(), state_c::state_c(), and voxel_c::voxel_c().
getTextCharacters()
const char * xmlParser_c::getTextCharacters (int * poslen)
References ENTITY_REF, name, TEXT, txtBuf, txtPos, and type.
initBuf()
void xmlParser_c::initBuf (void) private
References nspCounts, nspSize, srcBuf, srcBuflength, txtBuf, and txtBufSize.
Referenced by xmlParser_c(), and xmlParser_c().
isEmptyElementTag()
bool xmlParser_c::isEmptyElementTag (void)
References degenerated, exception(), illegal_type, START_TAG, and type.
isWhitespace()
bool xmlParser_c::isWhitespace (void)
References CDSECT, exception(), IGNORABLE_WHITESPACE, illegal_type, isWspace, TEXT, and type.
next()
int xmlParser_c::next (void)
go to the next xml event, and return the event type
References CDSECT, isWspace, nextImpl(), peekType(), TEXT, token, txtPos, and type.
Referenced by assembly_c::assembly_c(), nextTag(), nextText(), problem_c::problem_c(), pushText(), puzzle_c::puzzle_c(), separation_c::separation_c(), separationInfo_c::separationInfo_c(), skipSubTree(), state_c::state_c(), and voxel_c::voxel_c().
nextImpl()
void xmlParser_c::nextImpl (void) private
common base for next and nextToken.
Clears the state, except from txtPos and whitespace. Does not set the type variable
References attributeCount, degenerated, depth, END_DOCUMENT, END_TAG, ENTITY_REF, IGNORABLE_WHITESPACE, isWspace, name, Ns, parseEndTag(), parseLegacy(), parseStartTag(), peekType(), prefix, pushEntity(), pushText(), START_TAG, TEXT, text, token, type, and XML_DECL.
Referenced by next(), and nextToken().
nextTag()
int xmlParser_c::nextTag (void)
References END_DOCUMENT, END_TAG, exception(), isWspace, next(), skipNextTag, START_TAG, TEXT, and type.
Referenced by problem_c::problem_c(), puzzle_c::puzzle_c(), separation_c::separation_c(), solution_c::solution_c(), and state_c::state_c().
nextText()
std::string xmlParser_c::nextText (void)
References END_TAG, exception(), getText(), next(), START_TAG, TEXT, and type.
nextToken()
int xmlParser_c::nextToken (void)
References isWspace, nextImpl(), token, txtPos, and type.
parseDoctype()
void xmlParser_c::parseDoctype (bool push) private
precondition: &lt! consumed
References exception(), push(), read(), and unexpected_eof.
Referenced by parseLegacy().
parseEndTag()
void xmlParser_c::parseEndTag (void) private
References depth, elementStack, exception(), name, Ns, prefix, read(), readName(), relaxed, and skip().
Referenced by nextImpl().
parseLegacy()
int xmlParser_c::parseLegacy (bool push) private
References attributeCount, attributes, CDSECT, column, COMMENT, DOCDECL, encoding, exception(), isWspace, line, parseDoctype(), parseStartTag(), peekbuf(), PROCESSING_INSTRUCTION, push(), read(), relaxed, standalone, txtPos, unexpected_eof, version, and XML_DECL.
Referenced by nextImpl().
parseStartTag()
void xmlParser_c::parseStartTag (bool xmldecl) private
Sets name and attributes.
References attributeCount, attributes, degenerated, depth, elementStack, exception(), get(), getAttributeName(), name, Ns, nspCounts, nspSize, peekbuf(), prefix, pushText(), read(), readName(), relaxed, RESIZE_BUFFER, skip(), txtPos, and unexpected_eof.
Referenced by nextImpl(), and parseLegacy().
peekbuf()
int xmlParser_c::peekbuf (int pos) private
Does never read more than needed.
References peek, peekCount, reader, srcBuf, srcBuflength, srcCount, srcPos, and wasCR.
Referenced by parseLegacy(), parseStartTag(), peekType(), pushText(), read(), readName(), and skip().
peekType()
int xmlParser_c::peekType (void) private
References END_DOCUMENT, END_TAG, ENTITY_REF, LEGACY, peekbuf(), START_TAG, and TEXT.
Referenced by next(), and nextImpl().
prevTag()
void xmlParser_c::prevTag (void)
References skipNextTag.
push()
void xmlParser_c::push (int c) private
References isWspace, txtBuf, txtBufSize, and txtPos.
Referenced by parseDoctype(), parseLegacy(), pushEntity(), pushText(), and readName().
pushEntity()
void xmlParser_c::pushEntity (void) private
result: isWspace; if the setName parameter is set, the name of the entity is stored in "name"
References ENTITY_REF, entityMap, exception(), get(), name, parseInt(), push(), read(), relaxed, token, txtPos, type, unexpected_eof, and unresolved.
Referenced by nextImpl(), and pushText().
pushText()
void xmlParser_c::pushText (int delimiter, bool resolveEntities) private
types: '<': parse to any token (for nextToken ()) '"': parse to quote ' ': parse to whitespace or '>'
References next(), peekbuf(), push(), pushEntity(), read(), START_TAG, and type.
Referenced by nextImpl(), and parseStartTag().
read() [1/2]
int xmlParser_c::read (void) private
References column, line, peek, peekbuf(), and peekCount.
Referenced by parseDoctype(), parseEndTag(), parseLegacy(), parseStartTag(), pushEntity(), pushText(), read(), readName(), and skip().
read() [2/2]
void xmlParser_c::read (char c) private
References exception(), and read().
readName()
std::string xmlParser_c::readName (void) private
References exception(), get(), peekbuf(), push(), read(), and txtPos.
Referenced by parseEndTag(), and parseStartTag().
require()
void xmlParser_c::require (int type, std::string name)
check, if the parser is in a certain state.
type is one of the even type enum, name is used when a tag name is required, e.g
require(xmlParser_c::START_TAG, "puzzle")
to enforce that we are at an open puzzle tag
References exception(), getName(), state(), and type.
Referenced by assembly_c::assembly_c(), gridType_c::gridType_c(), problem_c::problem_c(), puzzle_c::puzzle_c(), separation_c::separation_c(), separationInfo_c::separationInfo_c(), skipSubTree(), solution_c::solution_c(), state_c::state_c(), and voxel_c::voxel_c().
skip()
void xmlParser_c::skip (void) private
References peekbuf(), and read().
Referenced by parseEndTag(), and parseStartTag().
skipSubTree()
void xmlParser_c::skipSubTree (void)
skip the complete tree until the close of the current tag.
Skip sub tree that is currently parser positioned on.
The stream must be at the beginning of a tag, otherwise an exception will be thrown
NOTE: parser must be on START_TAG and when funtion returns parser will be positioned on corresponding END_TAG.
References END_TAG, next(), require(), and START_TAG.
Referenced by gridType_c::gridType_c(), problem_c::problem_c(), puzzle_c::puzzle_c(), separation_c::separation_c(), and solution_c::solution_c().
state()
std::string xmlParser_c::state (int eventType) private
References CDSECT, COMMENT, DOCDECL, END_DOCUMENT, END_TAG, ENTITY_REF, IGNORABLE_WHITESPACE, PROCESSING_INSTRUCTION, START_DOCUMENT, START_TAG, and TEXT.
Referenced by exception(), and require().
Member Data Documentation
attributeCount
int xmlParser_c::attributeCount private
Referenced by commonInit(), getAttributeCount(), getAttributeName(), getAttributePrefix(), getAttributeValue(), getAttributeValue(), nextImpl(), parseLegacy(), and parseStartTag().
attributes
std::vector< std::string > xmlParser_c::attributes private
Referenced by getAttributeName(), getAttributePrefix(), getAttributeValue(), getAttributeValue(), parseLegacy(), and parseStartTag().
column
int xmlParser_c::column private
Referenced by commonInit(), exception(), parseLegacy(), and read().
degenerated
bool xmlParser_c::degenerated private
Referenced by commonInit(), isEmptyElementTag(), nextImpl(), and parseStartTag().
depth
int xmlParser_c::depth private
Referenced by commonInit(), getDepth(), nextImpl(), parseEndTag(), and parseStartTag().
elementStack
std::vector< std::string > xmlParser_c::elementStack private
Referenced by parseEndTag(), and parseStartTag().
encoding
std::string xmlParser_c::encoding private
Referenced by commonInit(), getInputEncoding(), and parseLegacy().
entityMap
std::map< std::string, std::string > xmlParser_c::entityMap private
Referenced by commonInit(), defineEntityReplacementText(), and pushEntity().
illegal_type
std::string xmlParser_c::illegal_type private
Referenced by isEmptyElementTag(), and isWhitespace().
isWspace
bool xmlParser_c::isWspace private
Referenced by isWhitespace(), next(), nextImpl(), nextTag(), nextToken(), parseLegacy(), and push().
LEGACY
int xmlParser_c::LEGACY private
Referenced by commonInit(), and peekType().
line
int xmlParser_c::line private
Referenced by commonInit(), exception(), parseLegacy(), and read().
name
std::string xmlParser_c::name private
Referenced by commonInit(), getName(), getTextCharacters(), nextImpl(), parseEndTag(), parseStartTag(), and pushEntity().
Ns
std::string xmlParser_c::Ns private
Referenced by commonInit(), nextImpl(), parseEndTag(), and parseStartTag().
nspCounts
int* xmlParser_c::nspCounts private
Referenced by commonInit(), initBuf(), parseStartTag(), and ~xmlParser_c().
nspSize
int xmlParser_c::nspSize private
Referenced by commonInit(), initBuf(), and parseStartTag().
nspStack
std::vector< std::string > xmlParser_c::nspStack private
peek
int xmlParser_c::peek[2] private
A separate peek buffer seems simpler than managing wrap around in the first level read buffer.
Referenced by peekbuf(), and read().
peekCount
int xmlParser_c::peekCount private
Referenced by commonInit(), peekbuf(), and read().
prefix
std::string xmlParser_c::prefix private
Referenced by getPrefix(), nextImpl(), parseEndTag(), and parseStartTag().
processNsp
bool xmlParser_c::processNsp private
reader
std::istream& xmlParser_c::reader private
Referenced by peekbuf().
relaxed
bool xmlParser_c::relaxed private
Referenced by commonInit(), parseEndTag(), parseLegacy(), parseStartTag(), and pushEntity().
skipNextTag
bool xmlParser_c::skipNextTag private
Referenced by commonInit(), nextTag(), and prevTag().
srcBuf
char* xmlParser_c::srcBuf private
Referenced by initBuf(), peekbuf(), and ~xmlParser_c().
srcBuflength
int xmlParser_c::srcBuflength private
Referenced by initBuf(), and peekbuf().
srcCount
int xmlParser_c::srcCount private
Referenced by commonInit(), and peekbuf().
srcPos
int xmlParser_c::srcPos private
Referenced by commonInit(), and peekbuf().
standalone
bool xmlParser_c::standalone private
Referenced by commonInit(), and parseLegacy().
text
std::string xmlParser_c::text private
Referenced by nextImpl().
token
bool xmlParser_c::token private
Referenced by next(), nextImpl(), nextToken(), and pushEntity().
txtBuf
char* xmlParser_c::txtBuf private
Referenced by get(), getTextCharacters(), initBuf(), push(), and ~xmlParser_c().
txtBufSize
int xmlParser_c::txtBufSize private
Referenced by initBuf(), and push().
txtPos
int xmlParser_c::txtPos private
Referenced by get(), getTextCharacters(), next(), nextToken(), parseLegacy(), parseStartTag(), push(), pushEntity(), and readName().
type
int xmlParser_c::type private
Referenced by commonInit(), exception(), getEventType(), getText(), getTextCharacters(), isEmptyElementTag(), isWhitespace(), next(), nextImpl(), nextTag(), nextText(), nextToken(), pushEntity(), pushText(), and require().
unexpected_eof
std::string xmlParser_c::unexpected_eof private
Referenced by parseDoctype(), parseLegacy(), parseStartTag(), and pushEntity().
unresolved
bool xmlParser_c::unresolved private
Referenced by commonInit(), getText(), and pushEntity().
version
std::string xmlParser_c::version private
Referenced by commonInit(), and parseLegacy().
wasCR
bool xmlParser_c::wasCR private
Referenced by peekbuf().
XML_DECL
int xmlParser_c::XML_DECL private
Referenced by commonInit(), nextImpl(), and parseLegacy().
The documentation for this class was generated from the following files:
src/tools/xml.h
src/tools/xml.cpp