BurrTools: disassembler_0_c Class Reference
disassembler_0_c Class Reference
This class is a disassembler especially tuned for simple analysis.
#include <disassembler_0.h>
Public Member Functions
disassembler_0_c (const problem_c &puz)
~disassembler_0_c ()
Public Member Functions inherited from disassembler_a_c
disassembler_a_c (const problem_c &puz)
construct the disassembler for this concrete problem.
~disassembler_a_c (void)
separation_c * disassemble (const assembly_c *assembly)
Disassemble an assembly of the puzzle.
Public Member Functions inherited from disassembler_c
disassembler_c (void)
virtual ~disassembler_c (void)
Private Member Functions
separation_c * disassemble_rec (const std::vector< unsigned int > &pieces, disassemblerNode_c *start)
The real disassembly routine.
disassembler_0_c (const disassembler_0_c &)
void operator= (const disassembler_0_c &)
Additional Inherited Members
Protected Member Functions inherited from disassembler_a_c
void init_find (disassemblerNode_c *nd, const std::vector< unsigned int > &pieces)
start analysing the position given in the disassemblerNode
disassemblerNode_c * find (void)
get one possible next position for the currently running analysis
separation_c * checkSubproblems (const disassemblerNode_c *st, const std::vector< unsigned int > &pieces)
Analyse a sub-problem.
Detailed Description
This class is a disassembler especially tuned for simple analysis.
All involved steps are of size one. This enables us to use a simple tree search instead of A* which would normally be required for a graph search
Constructor & Destructor Documentation
disassembler_0_c() [1/2]
disassembler_0_c::disassembler_0_c (const problem_c & puz) inline
~disassembler_0_c()
disassembler_0_c::~disassembler_0_c () inline
disassembler_0_c() [2/2]
disassembler_0_c::disassembler_0_c (const disassembler_0_c &) private
Member Function Documentation
disassemble_rec()
separation_c * disassembler_0_c::disassemble_rec (const std::vector< unsigned int > & pieces, disassemblerNode_c * start) private virtual
The real disassembly routine.
It separates the puzzle into 2 parts and gets called recursively with each subpart to disassemble
the return is the disassembly tree for that part
pieces contains the names of all the pieces that are still inside the subpuzzle puzzle, start defines the starting position of these pieces
Implements disassembler_a_c.
References disassembler_a_c::checkSubproblems(), nodeHash::clear(), disassemblerNode_c::decRefCount(), disassembler_a_c::find(), disassembler_a_c::init_find(), nodeHash::insert(), and disassemblerNode_c::is_separation().
operator=()
void disassembler_0_c::operator= (const disassembler_0_c &) private
The documentation for this class was generated from the following files:
src/lib/disassembler_0.h
src/lib/disassembler_0.cpp