BurrTools: src/lib/converter.cpp File Reference
converter.cpp File Reference
#include "converter.h"
#include "puzzle.h"
#include "problem.h"
#include "voxel.h"
Functions
bool canConvert (gridType_c::gridType src, gridType_c::gridType dst)
returns true, if it is possible to convert this puzzle to the given gridType
puzzle_c * doConvert (puzzle_c *p, gridType_c::gridType type)
Create a new puzzle with a new gridtype but identical shapes.
Function Documentation
canConvert()
bool canConvert (gridType_c::gridType src, gridType_c::gridType dst)
returns true, if it is possible to convert this puzzle to the given gridType
References gridType_c::GT_BRICKS, gridType_c::GT_RHOMBIC, and gridType_c::GT_TETRA_OCTA.
Referenced by doConvert().
doConvert()
puzzle_c * doConvert (puzzle_c * p, gridType_c::gridType type)
Create a new puzzle with a new gridtype but identical shapes.
If the conversion can't be done (you should check first with canConvert) a NULL pointer will be returned
References puzzle_c::addColor(), puzzle_c::addProblem(), puzzle_c::addShape(), bt_assert, canConvert(), puzzle_c::colorNumber(), voxel_c::get(), puzzle_c::getColor(), puzzle_c::getComment(), puzzle_c::getCommentPopup(), puzzle_c::getGridType(), problem_c::getName(), voxel_c::getName(), puzzle_c::getNumberOfProblems(), puzzle_c::getNumberOfShapes(), puzzle_c::getProblem(), puzzle_c::getShape(), gridType_c::getType(), gridType_c::getVoxel(), voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), gridType_c::GT_BRICKS, gridType_c::GT_RHOMBIC, gridType_c::GT_TETRA_OCTA, voxel_c::set(), puzzle_c::setComment(), puzzle_c::setCommentPopup(), voxel_c::setName(), problem_c::setName(), voxel_c::skipRecalcBoundingBox(), voxel_c::validCoordinate(), and voxel_c::VX_EMPTY.