BurrTools: src/lib/disassembler_a.cpp File Reference
disassembler_a.cpp File Reference
#include "disassembler_a.h"
#include "bt_assert.h"
#include "problem.h"
#include "grouping.h"
#include "disassemblernode.h"
#include "movementanalysator.h"
#include "assembly.h"
#include "disassembly.h"
Functions
static void create_new_params (const disassemblerNode_c *st, disassemblerNode_c **n, std::vector< unsigned int > &pn, const std::vector< unsigned int > &pieces, int part, bool cond)
Function Documentation
create_new_params()
static void create_new_params (const disassemblerNode_c * st, disassemblerNode_c ** n, std::vector< unsigned int > & pn, const std::vector< unsigned int > & pieces, int part, bool cond) static
References bt_assert, disassemblerNode_c::getComefrom(), disassemblerNode_c::getTrans(), disassemblerNode_c::getX(), disassemblerNode_c::getY(), disassemblerNode_c::getZ(), and disassemblerNode_c::is_piece_removed().
Referenced by disassembler_a_c::checkSubproblem().