BurrTools: src/tools/intdiv.h File Reference
intdiv.h File Reference
Functions
template<class T >
T intdiv_inf (T x, T y)
Integer division with round towards minus infinity,.
Function Documentation
intdiv_inf()
template<class T > T intdiv_inf (T x, T y) inline
Integer division with round towards minus infinity,.
taken from python The type must be a signed integer type
Referenced by voxel_3_c::getConnectionFace(), voxel_4_c::getConnectionFace(), voxel_3_c::getNeighbor(), voxel_4_c::getNeighbor(), and voxel_4_c::validCoordinate().