BurrTools: src/lib/millable.h File Reference
millable.h File Reference
Functions
bool isNotchable (const voxel_c *v)
Check, if a piece is notchable.
bool isMillable (const voxel_c *v)
Check, if a shape is millable.
Function Documentation
isMillable()
bool isMillable (const voxel_c * v)
Check, if a shape is millable.
a piece is millable, if it contains no inside corners
This function only works for cube voxel spaces right now
References voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), voxel_c::isEmpty(), and voxel_c::isFilled2().
isNotchable()
bool isNotchable (const voxel_c * v)
Check, if a piece is notchable.
a piece is notchable, if it can be made purely by cutting
This function only works for cube voxel spaces right now
References voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), gridType_c::GT_BRICKS, voxel_c::isFilled(), voxel_c::set(), and voxel_c::VX_FILLED.