BurrTools: src/lib/movementanalysator.cpp File Reference
movementanalysator.cpp File Reference
#include "movementanalysator.h"
#include "bt_assert.h"
#include "movementcache.h"
#include "problem.h"
#include "puzzle.h"
#include "disassemblernode.h"
#include "voxel.h"
#include "disassemblerhashes.h"
#include "gridtype.h"
#include <string.h>
Functions
static int max (int a, int b)
Function Documentation
max()
static int max (int a, int b) static
Referenced by problem_c::exchangeParts(), problem_c::getNumberOfPieces(), problem_c::getPartIdToPieceId(), problem_c::getPartIndexToPieceId(), movementCache_0_c::moCalcValues(), movementAnalysator_c::newNode(), printMatrix(), problem_c::problem_c(), problem_c::save(), problem_c::setShapeMaximum(), and problem_c::setShapeMinimum().