BurrTools: src/lib/print.cpp File Reference
print.cpp File Reference
#include "print.h"
#include "voxel.h"
#include "puzzle.h"
#include "problem.h"
#include "disassembly.h"
#include "assembly.h"
#include "assert.h"
Functions
void print (const voxel_c *v, char base)
void print (const puzzle_c *p)
static void print_rec (const separation_c *s, voxel_c **pieces, int sx, int sy, int sz, unsigned int *pieceNum)
void print (const separation_c *s, const assembly_c *a, const problem_c *p)
void print (const assembly_c *a, const problem_c *p)
Function Documentation
print() [1/4]
void print (const assembly_c * a, const problem_c * p)
References bt_assert, bt_assert2, puzzle_c::getGridType(), voxel_c::getHx(), voxel_c::getHy(), voxel_c::getHz(), problem_c::getNumberOfParts(), problem_c::getPartMaximum(), problem_c::getPartShape(), problem_c::getPuzzle(), getResultShape(), assembly_c::getTransformation(), gridType_c::getVoxel(), assembly_c::getX(), voxel_c::getX(), assembly_c::getY(), voxel_c::getY(), assembly_c::getZ(), voxel_c::getZ(), assembly_c::isPlaced(), assembly_c::placementCount(), and problem_c::resultValid().
print() [2/4]
void print (const puzzle_c * p)
References problem_c::getName(), problem_c::getNumberOfParts(), puzzle_c::getNumberOfProblems(), puzzle_c::getNumberOfShapes(), problem_c::getPartMaximum(), problem_c::getPartMinimum(), puzzle_c::getProblem(), problem_c::getResultId(), puzzle_c::getShape(), problem_c::getShapeIdOfPart(), print(), and problem_c::resultValid().
print() [3/4]
void print (const separation_c * s, const assembly_c * a, const problem_c * p)
References bt_assert, bt_assert2, puzzle_c::getGridType(), problem_c::getNumberOfParts(), problem_c::getPartMaximum(), problem_c::getPartShape(), problem_c::getPuzzle(), getResultShape(), assembly_c::getTransformation(), gridType_c::getVoxel(), voxel_c::getX(), voxel_c::getY(), voxel_c::getZ(), assembly_c::placementCount(), print_rec(), and problem_c::resultValid().
print() [4/4]
void print (const voxel_c * v, char base)
References voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), voxel_c::get(), voxel_c::getHx(), voxel_c::getHy(), voxel_c::getHz(), voxel_c::getX(), voxel_c::getY(), and voxel_c::getZ().
Referenced by print().
print_rec()
static void print_rec (const separation_c * s, voxel_c ** pieces, int sx, int sy, int sz, unsigned int * pieceNum) static
References voxel_c::getHx(), voxel_c::getHy(), voxel_c::getHz(), separation_c::getLeft(), separation_c::getMoves(), separation_c::getPieceNumber(), separation_c::getRemoved(), separation_c::getState(), state_c::getX(), state_c::getY(), state_c::getZ(), state_c::pieceRemoved(), and print_rec().
Referenced by print(), and print_rec().