BurrTools: src/lib/problem.h File Reference
problem.h File Reference
#include "assembler.h"
#include "bt_assert.h"
#include <stdint.h>
#include <vector>
#include <set>
#include <string>
Classes
class problem_c
This class defines a problem,.
Enumerations
enum solveState_e { SS_UNSOLVED , SS_SOLVING , SS_SOLVED , SS_UNKNOWN }
this state reflects how far we are with solving this problem
Functions
const voxel_c * getResultShape (const problem_c &problem)
get the voxel space of the result shape.
voxel_c * getResultShape (problem_c &problem)
get the voxel space of the result shape.
Enumeration Type Documentation
solveState_e
enum solveState_e
this state reflects how far we are with solving this problem
Enumerator
SS_UNSOLVED
nothing done yet
SS_SOLVING
started and not finished in this state assm must contain the assembler
SS_SOLVED
finished, the assembler has been destroyed and all the information is available
SS_UNKNOWN
Function Documentation
getResultShape() [1/2]
const voxel_c * getResultShape (const problem_c & problem)
get the voxel space of the result shape.
Make sure to only call getResultId[Shape] when you know that the shape is valid
References bt_assert, problem_c::getPuzzle(), problem_c::getResultId(), puzzle_c::getShape(), and problem_c::resultValid().
Referenced by assembler_0_c::canPlace(), assembler_1_c::canPlace(), assembler_0_c::createMatrix(), assembler_1_c::createMatrix(), assembler_1_c::prepare(), assembler_0_c::prepare(), print(), print(), assembly_c::smallerRotationExists(), and assembly_c::transform().
getResultShape() [2/2]
voxel_c * getResultShape (problem_c & problem)
get the voxel space of the result shape.
Make sure to only call getResultId[Shape] when you know that the shape is valid
References bt_assert, problem_c::getPuzzle(), problem_c::getResultId(), puzzle_c::getShape(), and problem_c::resultValid().