BurrTools: src/lib/problem.cpp File Reference
problem.cpp File Reference
#include "problem.h"
#include "bt_assert.h"
#include "voxel.h"
#include "assembly.h"
#include "disassembly.h"
#include "puzzle.h"
#include "solution.h"
#include "../tools/xml.h"
#include <algorithm>
#include <stdio.h>
Classes
class group_c
internal class of problem storing the grouping information of a shape
class part_c
internal class of problem storing the information attached to a piece in a problem
Functions
const voxel_c * getResultShape (const problem_c &problem)
get the voxel space of the result shape.
voxel_c * getResultShape (problem_c &problem)
get the voxel space of the result shape.
static bool comp_0_assembly (const solution_c *s1, const solution_c *s2)
static bool comp_1_level (solution_c *s1, solution_c *s2)
static bool comp_2_moves (solution_c *s1, solution_c *s2)
static bool comp_3_pieces (const solution_c *s1, const solution_c *s2)
Function Documentation
comp_0_assembly()
static bool comp_0_assembly (const solution_c * s1, const solution_c * s2) static
References solution_c::getAssemblyNumber().
Referenced by problem_c::sortSolutions().
comp_1_level()
static bool comp_1_level (solution_c * s1, solution_c * s2) static
References disassembly_c::compare(), and solution_c::getDisassemblyInfo().
Referenced by problem_c::sortSolutions().
comp_2_moves()
static bool comp_2_moves (solution_c * s1, solution_c * s2) static
References solution_c::getDisassemblyInfo(), and disassembly_c::sumMoves().
Referenced by problem_c::sortSolutions().
comp_3_pieces()
static bool comp_3_pieces (const solution_c * s1, const solution_c * s2) static
References assembly_c::comparePieces(), and solution_c::getAssembly().
Referenced by problem_c::sortSolutions().
getResultShape() [1/2]
const voxel_c * getResultShape (const problem_c & problem)
get the voxel space of the result shape.
Make sure to only call getResultId[Shape] when you know that the shape is valid
References bt_assert, problem_c::getPuzzle(), problem_c::getResultId(), puzzle_c::getShape(), and problem_c::resultValid().
Referenced by assembler_0_c::canPlace(), assembler_1_c::canPlace(), assembler_0_c::createMatrix(), assembler_1_c::createMatrix(), assembler_1_c::prepare(), assembler_0_c::prepare(), print(), print(), assembly_c::smallerRotationExists(), and assembly_c::transform().
getResultShape() [2/2]
voxel_c * getResultShape (problem_c & problem)
get the voxel space of the result shape.
Make sure to only call getResultId[Shape] when you know that the shape is valid
References bt_assert, problem_c::getPuzzle(), problem_c::getResultId(), puzzle_c::getShape(), and problem_c::resultValid().