BurrTools: src/lib/ps3dloader.cpp File Reference
ps3dloader.cpp File Reference
#include "ps3dloader.h"
#include "voxel.h"
#include "puzzle.h"
#include "problem.h"
#include "gridtype.h"
#include <fstream>
#include <sstream>
Functions
puzzle_c * loadPuzzlerSolver3D (std::istream *str)
Function Documentation
loadPuzzlerSolver3D()
puzzle_c * loadPuzzlerSolver3D (std::istream * str)
References puzzle_c::addProblem(), puzzle_c::addShape(), problem_c::getNumberOfParts(), problem_c::getPartShape(), puzzle_c::getProblem(), puzzle_c::getShape(), problem_c::getShapeIdOfPart(), problem_c::getShapeMaximum(), problem_c::getShapeMinimum(), voxel_c::identicalWithRots(), voxel_c::setName(), problem_c::setName(), problem_c::setResultId(), problem_c::setShapeMaximum(), problem_c::setShapeMinimum(), voxel_c::setState(), and voxel_c::VX_FILLED.