BurrTools: src/lib/voxeltable.cpp File Reference
voxeltable.cpp File Reference
#include "voxeltable.h"
#include "voxel.h"
#include "puzzle.h"
Functions
static unsigned long calcHashValue (const voxel_c *v)
static unsigned long calcColourHashValue (const voxel_c *v)
Function Documentation
calcColourHashValue()
static unsigned long calcColourHashValue (const voxel_c * v) static
References voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), voxel_c::getColor(), voxel_c::getState(), and voxel_c::VX_EMPTY.
Referenced by voxelTable_c::addSpace(), and voxelTable_c::getSpace().
calcHashValue()
static unsigned long calcHashValue (const voxel_c * v) static
References voxel_c::boundX1(), voxel_c::boundX2(), voxel_c::boundY1(), voxel_c::boundY2(), voxel_c::boundZ1(), voxel_c::boundZ2(), and voxel_c::getState().
Referenced by voxelTable_c::addSpace(), and voxelTable_c::getSpace().