BurrTools: src/tools/xml.cpp File Reference
xml.cpp File Reference
#include "xml.h"
#include <string.h>
#include <sstream>
Functions
static void outIndent (std::ostream &s, size_t cnt)
static void outString (std::ostream &stream, const std::string &text)
static int parseInt (std::string s, int radix)
Variables
static const int RESIZE_BUFFER = 16
Function Documentation
outIndent()
static void outIndent (std::ostream & s, size_t cnt) static
Referenced by xmlWriter_c::endTag(), and xmlWriter_c::newTag().
outString()
static void outString (std::ostream & stream, const std::string & text) static
Referenced by xmlWriter_c::addContent(), and xmlWriter_c::newAttrib().
parseInt()
static int parseInt (std::string s, int radix) static
Referenced by xmlParser_c::pushEntity().
Variable Documentation
RESIZE_BUFFER
const int RESIZE_BUFFER = 16 static
Referenced by xmlParser_c::parseStartTag().